// Export pages
export '/features/onboarding/presentation/pages/welcome_page.dart'
    show WelcomePage;
export '/features/auth/presentation/pages/login_technician_page.dart'
    show LoginTechnicianPage;
export '/features/auth/presentation/pages/create_account_technician_page.dart'
    show CreateAccountTechnicianPage;
export '/features/dashboard/presentation/pages/dashboard_tecnico_page.dart'
    show DashboardTecnicoPage;
export '/features/propriedades/presentation/pages/lista_propriedade_page.dart'
    show ListaPropriedadePage;
export '/features/propriedades/presentation/pages/nova_propriedade_page.dart'
    show NovaPropriedadePage;
export '/features/propriedades/presentation/pages/inicio_propriedade_page.dart'
    show InicioPropriedadePage;
export '/features/propriedades/presentation/pages/editar_propriedade_page.dart'
    show EditarPropriedadePage;
export '/features/propriedades/presentation/pages/propriedades_excluidas_page.dart'
    show PropriedadesExcluiasPage;
export '/features/animais/presentation/pages/cadastrar_novo_animal_page.dart'
    show CadastrarNovoAnimalPage;
export '/features/animais/presentation/pages/lista_animais_page.dart'
    show ListaAnimaisPage;
export '/features/inseminacoes/presentation/pages/lista_inseminacoes_page.dart'
    show ListaInseminacoesPage;
export '/features/exame_ginecologico/presentation/pages/exame_ginecologico_page.dart'
    show ExameGinecologicoPage;
export '/features/prenhas/presentation/pages/animais_prenhas_page.dart'
    show AnimaisPrenhasPage;
export '/features/secas/presentation/pages/secas_page.dart' show SecasPage;
export '/features/auth/presentation/pages/sync_technician_page.dart'
    show SyncTechnicianPage;
export '/features/receituario/presentation/pages/receituarios_lista_page.dart'
    show ReceituariosListaPage;
export '/features/receituario/presentation/pages/resumo_visita_atual_page.dart'
    show ResumoVisitaAtualPage;
export '/features/relatorios/presentation/pages/resumo_rebanho_page.dart'
    show ResumoRebanhoPage;
export '/features/relatorios/presentation/pages/indices_zootecnicos_page.dart'
    show IndicesZootecnicosPage;
export '/features/perfil/presentation/pages/completar_perfil_tecnico_page.dart'
    show CompletarPerfilTecnicoPage;
export '/features/produtor/presentation/pages/login_produtor_page.dart'
    show LoginProdutorPage;
export '/features/onboarding/presentation/pages/tutorial_page.dart'
    show TutorialPage;
export '/features/perfil/presentation/pages/profile_tecnico_page.dart'
    show ProfileTecnicoPage;
export '/features/plano/presentation/pages/subscription_plan_tecnico_page.dart'
    show SubscriptionPlanTecnicoPage;
export '/features/prontuario/presentation/pages/prontuario_animal_page.dart'
    show ProntuarioAnimalPage;
export '/features/animais/presentation/pages/editar_animal_page.dart'
    show EditarAnimalPage;
export '/features/prontuario/presentation/pages/pron_inseminacoes_page.dart'
    show PronInseminacoesPage;
export '/features/prontuario/presentation/pages/pron_acoes_page.dart'
    show PronAcoesPage;
export '/features/prontuario/presentation/pages/pron_abortos_page.dart'
    show PronAbortosPage;
export '/features/prontuario/presentation/pages/pron_diag_gestacao_page.dart'
    show PronDiagGestacaoPage;
export '/features/prontuario/presentation/pages/pron_cios_page.dart'
    show PronCiosPage;
export '/features/diagnostico_gestacao/presentation/pages/diagnosticogestacao_page.dart'
    show DiagnosticogestacaoPage;
export '/features/calendario_sanitario/presentation/pages/calendario_sanitario_page.dart'
    show CalendarioSanitarioPage;
export '/features/financeiro/presentation/pages/relatorio_financeiro_page.dart'
    show RelatorioFinanceiroPage;
export '/features/financeiro/presentation/pages/novo_relatorio_financeiro_page.dart'
    show NovoRelatorioFinanceiroPage;
export '/features/relatorios/presentation/pages/listacompleta_page.dart'
    show ListacompletaPage;
export '/features/perfil/presentation/pages/apagar_conta_page.dart'
    show ApagarContaPage;
export '/features/financeiro/presentation/pages/editar_relatorio_financeiro_page.dart'
    show EditarRelatorioFinanceiroPage;
export '/features/recria/presentation/pages/recriacao_page.dart'
    show RecriacaoPage;
export '/features/sincronizacao/presentation/pages/importacao_animais_page.dart'
    show ImportacaoAnimaisPage;
export '/features/produtor/presentation/pages/inicio_propriedade_produtor_page.dart'
    show InicioPropriedadeProdutorPage;
export '/features/onboarding/presentation/pages/verifica_tipo_login_page.dart'
    show VerificaTipoLoginPage;
