// Exporta as telas
export '/screens/welcome/welcome/welcome_widget.dart' show WelcomeWidget;
export '/screens/tecnico/initial/login_technician/login_technician_widget.dart'
    show LoginTechnicianWidget;
export '/screens/tecnico/initial/create_account_technician/create_account_technician_widget.dart'
    show CreateAccountTechnicianWidget;
export '/screens/tecnico/dashboard/dashboard_tecnico/dashboard_tecnico_widget.dart'
    show DashboardTecnicoWidget;
export '/screens/tecnico/propriedade/propriedades/lista_propriedade/lista_propriedade_widget.dart'
    show ListaPropriedadeWidget;
export '/screens/tecnico/propriedade/propriedades/nova_propriedade/nova_propriedade_widget.dart'
    show NovaPropriedadeWidget;
export '/screens/tecnico/propriedade/inicio_propriedade/inicio_propriedade_widget.dart'
    show InicioPropriedadeWidget;
export '/screens/tecnico/propriedade/propriedades/editar_propriedade/editar_propriedade_widget.dart'
    show EditarPropriedadeWidget;
export '/screens/tecnico/propriedade/animals/cadastrar_novo_animal/cadastrar_novo_animal_widget.dart'
    show CadastrarNovoAnimalWidget;
export '/screens/tecnico/propriedade/animals/lista_animais/lista_animais_widget.dart'
    show ListaAnimaisWidget;
export '/screens/tecnico/propriedade/inseminacoes/lista_inseminacoes/lista_inseminacoes_widget.dart'
    show ListaInseminacoesWidget;
export '/screens/tecnico/propriedade/exame_ginecologico/exame_ginecologico/exame_ginecologico_widget.dart'
    show ExameGinecologicoWidget;
export '/screens/tecnico/propriedade/prenhas/animais_prenhas/animais_prenhas_widget.dart'
    show AnimaisPrenhasWidget;
export '/screens/tecnico/propriedade/secas/secas/secas_widget.dart'
    show SecasWidget;
export '/screens/tecnico/initial/sync_technician/sync_technician_widget.dart'
    show SyncTechnicianWidget;
export '/screens/tecnico/propriedade/receituario/receituarios_lista/receituarios_lista_widget.dart'
    show ReceituariosListaWidget;
export '/screens/tecnico/propriedade/receituario/resumo_visita_atual/resumo_visita_atual_widget.dart'
    show ResumoVisitaAtualWidget;
export '/screens/tecnico/propriedade/resumo_rebanho/resumo_rebanho/resumo_rebanho_widget.dart'
    show ResumoRebanhoWidget;
export '/screens/tecnico/propriedade/indices_zootecnicos/indices_zootecnicos/indices_zootecnicos_widget.dart'
    show IndicesZootecnicosWidget;
export '/screens/tecnico/perfil/completar_perfil_tecnico/completar_perfil_tecnico_widget.dart'
    show CompletarPerfilTecnicoWidget;
export '/screens/produtor/initial/login_produtor/login_produtor_widget.dart'
    show LoginProdutorWidget;
export '/screens/welcome/tutorial/tutorial_widget.dart' show TutorialWidget;
export '/screens/tecnico/perfil/profile_tecnico/profile_tecnico_widget.dart'
    show ProfileTecnicoWidget;
export '/screens/tecnico/plano/subscription_plan_tecnico/subscription_plan_tecnico_widget.dart'
    show SubscriptionPlanTecnicoWidget;
export '/screens/tecnico/propriedade/prontuario/prontuario_animal/prontuario_animal_widget.dart'
    show ProntuarioAnimalWidget;
export '/screens/tecnico/propriedade/animals/editar_animal/editar_animal_widget.dart'
    show EditarAnimalWidget;
export '/screens/tecnico/propriedade/prontuario/pron_inseminacoes/pron_inseminacoes_widget.dart'
    show PronInseminacoesWidget;
export '/screens/tecnico/propriedade/prontuario/pron_acoes/pron_acoes_widget.dart'
    show PronAcoesWidget;
export '/screens/tecnico/propriedade/prontuario/pron_abortos/pron_abortos_widget.dart'
    show PronAbortosWidget;
export '/screens/tecnico/propriedade/prontuario/pron_diag_gestacao/pron_diag_gestacao_widget.dart'
    show PronDiagGestacaoWidget;
export '/screens/tecnico/propriedade/prontuario/pron_cios/pron_cios_widget.dart'
    show PronCiosWidget;
export '/screens/tecnico/propriedade/dignostico_gestacao/diagnosticogestacao/diagnosticogestacao_widget.dart'
    show DiagnosticogestacaoWidget;
export '/screens/tecnico/propriedade/calendario_sanitario/calendario_sanitario/calendario_sanitario_widget.dart'
    show CalendarioSanitarioWidget;
export '/screens/tecnico/propriedade/financeiro/relatorio_financeiro/relatorio_financeiro_widget.dart'
    show RelatorioFinanceiroWidget;
export '/screens/tecnico/propriedade/financeiro/novo_relatorio_financeiro/novo_relatorio_financeiro_widget.dart'
    show NovoRelatorioFinanceiroWidget;
export '/screens/tecnico/propriedade/lista_completa/listacompleta/listacompleta_widget.dart'
    show ListacompletaWidget;
export '/screens/tecnico/perfil/apagar_conta/apagar_conta_widget.dart'
    show ApagarContaWidget;
export '/screens/tecnico/propriedade/financeiro/editar_relatorio_financeiro/editar_relatorio_financeiro_widget.dart'
    show EditarRelatorioFinanceiroWidget;
export '/screens/tecnico/propriedade/recria/recriacao/recriacao_widget.dart'
    show RecriacaoWidget;
export '/screens/tecnico/propriedade/inseminacoes/lista_inseminacoes_antes_offline/lista_inseminacoes_antes_offline_widget.dart'
    show ListaInseminacoesAntesOfflineWidget;
export '/screens/tecnico/propriedade/prontuario/prontuario_animal_offline/prontuario_animal_offline_widget.dart'
    show ProntuarioAnimalOfflineWidget;
export '/screens/tecnico/propriedade/dignostico_gestacao/diagnosticogestacao_modo1_off/diagnosticogestacao_modo1_off_widget.dart'
    show DiagnosticogestacaoModo1OffWidget;
export '/screens/tecnico/propriedade/sincronizacao/acoes_falhadas/acoes_falhadas_widget.dart'
    show AcoesFalhadasWidget;
export '/screens/tecnico/propriedade/sincronizacao/importacao_animais/importacao_animais_widget.dart'
    show ImportacaoAnimaisWidget;
export '/screens/produtor/initial/inicio_propriedade_produtor/inicio_propriedade_produtor_widget.dart'
    show InicioPropriedadeProdutorWidget;
export '/screens/welcome/verifica_tipo_login/verifica_tipo_login_widget.dart'
    show VerificaTipoLoginWidget;
