// Export pages
export '/features/onboarding/presentation/pages/welcome_page.dart'
    show WelcomePage;
export '/features/auth/presentation/pages/login_technician_page.dart'
    show LoginTechnicianPage;
export '/features/auth/presentation/pages/create_account_technician_page.dart'
    show CreateAccountTechnicianPage;
export '/pages/tecnico/dashboard/dashboard_tecnico/dashboard_tecnico_widget.dart'
    show DashboardTecnicoWidget;
export '/pages/tecnico/propriedade/propriedades/lista_propriedade/lista_propriedade_widget.dart'
    show ListaPropriedadeWidget;
export '/pages/tecnico/propriedade/propriedades/nova_propriedade/nova_propriedade_widget.dart'
    show NovaPropriedadeWidget;
export '/pages/tecnico/propriedade/inicio_propriedade/inicio_propriedade_widget.dart'
    show InicioPropriedadeWidget;
export '/pages/tecnico/propriedade/propriedades/editar_propriedade/editar_propriedade_widget.dart'
    show EditarPropriedadeWidget;
export '/pages/tecnico/propriedade/propriedades/propriedades_excluidas/propriedades_excluidas_widget.dart'
    show PropriedadesExcluiasWidget;
export '/pages/tecnico/propriedade/animals/cadastrar_novo_animal/cadastrar_novo_animal_widget.dart'
    show CadastrarNovoAnimalWidget;
export '/pages/tecnico/propriedade/animals/lista_animais/lista_animais_widget.dart'
    show ListaAnimaisWidget;
export '/pages/tecnico/propriedade/inseminacoes/lista_inseminacoes/lista_inseminacoes_widget.dart'
    show ListaInseminacoesWidget;
export '/pages/tecnico/propriedade/exame_ginecologico/exame_ginecologico/exame_ginecologico_widget.dart'
    show ExameGinecologicoWidget;
export '/pages/tecnico/propriedade/prenhas/animais_prenhas/animais_prenhas_widget.dart'
    show AnimaisPrenhasWidget;
export '/pages/tecnico/propriedade/secas/secas/secas_widget.dart'
    show SecasWidget;
export '/pages/tecnico/initial/sync_technician/sync_technician_widget.dart'
    show SyncTechnicianWidget;
export '/pages/tecnico/propriedade/receituario/receituarios_lista/receituarios_lista_widget.dart'
    show ReceituariosListaWidget;
export '/pages/tecnico/propriedade/receituario/resumo_visita_atual/resumo_visita_atual_widget.dart'
    show ResumoVisitaAtualWidget;
export '/pages/tecnico/propriedade/resumo_rebanho/resumo_rebanho/resumo_rebanho_widget.dart'
    show ResumoRebanhoWidget;
export '/pages/tecnico/propriedade/indices_zootecnicos/indices_zootecnicos/indices_zootecnicos_widget.dart'
    show IndicesZootecnicosWidget;
export '/pages/tecnico/perfil/completar_perfil_tecnico/completar_perfil_tecnico_widget.dart'
    show CompletarPerfilTecnicoWidget;
export '/features/produtor/presentation/pages/login_produtor_page.dart'
    show LoginProdutorPage;
export '/features/onboarding/presentation/pages/tutorial_page.dart'
    show TutorialPage;
export '/features/perfil/presentation/pages/profile_tecnico_page.dart'
    show ProfileTecnicoPage;
export '/pages/tecnico/plano/subscription_plan_tecnico/subscription_plan_tecnico_widget.dart'
    show SubscriptionPlanTecnicoWidget;
export '/pages/tecnico/propriedade/prontuario/prontuario_animal/prontuario_animal_widget.dart'
    show ProntuarioAnimalWidget;
export '/pages/tecnico/propriedade/animals/editar_animal/editar_animal_widget.dart'
    show EditarAnimalWidget;
export '/features/prontuario/presentation/pages/pron_inseminacoes_page.dart'
    show PronInseminacoesPage;
export '/features/prontuario/presentation/pages/pron_acoes_page.dart'
    show PronAcoesPage;
export '/features/prontuario/presentation/pages/pron_abortos_page.dart'
    show PronAbortosPage;
export '/features/prontuario/presentation/pages/pron_diag_gestacao_page.dart'
    show PronDiagGestacaoPage;
export '/features/prontuario/presentation/pages/pron_cios_page.dart'
    show PronCiosPage;
export '/pages/tecnico/propriedade/dignostico_gestacao/diagnosticogestacao/diagnosticogestacao_widget.dart'
    show DiagnosticogestacaoWidget;
export '/pages/tecnico/propriedade/calendario_sanitario/calendario_sanitario/calendario_sanitario_widget.dart'
    show CalendarioSanitarioWidget;
export '/pages/tecnico/propriedade/financeiro/relatorio_financeiro/relatorio_financeiro_widget.dart'
    show RelatorioFinanceiroWidget;
export '/pages/tecnico/propriedade/financeiro/novo_relatorio_financeiro/novo_relatorio_financeiro_widget.dart'
    show NovoRelatorioFinanceiroWidget;
export '/pages/tecnico/propriedade/lista_completa/listacompleta/listacompleta_widget.dart'
    show ListacompletaWidget;
export '/features/perfil/presentation/pages/apagar_conta_page.dart'
    show ApagarContaPage;
export '/pages/tecnico/propriedade/financeiro/editar_relatorio_financeiro/editar_relatorio_financeiro_widget.dart'
    show EditarRelatorioFinanceiroWidget;
export '/features/recria/presentation/pages/recriacao_page.dart'
    show RecriacaoPage;
export '/pages/tecnico/propriedade/sincronizacao/importacao_animais/importacao_animais_widget.dart'
    show ImportacaoAnimaisWidget;
export '/pages/produtor/initial/inicio_propriedade_produtor/inicio_propriedade_produtor_widget.dart'
    show InicioPropriedadeProdutorWidget;
export '/features/onboarding/presentation/pages/verifica_tipo_login_page.dart'
    show VerificaTipoLoginPage;
