// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'backend/objectbox/entities/animal_entity.dart';
import 'backend/objectbox/entities/person_entity.dart';
import 'backend/objectbox/entities/produtor_entity.dart';
import 'backend/objectbox/entities/propriedade_entity.dart';
import 'backend/objectbox/entities/sync_metadata_entity.dart';
import 'backend/objectbox/entities/tecnico_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8986228835005611182),
    name: 'AnimalEntity',
    lastPropertyId: const obx_int.IdUid(44, 7363795320818029985),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8422760424833753736),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8982918733280263257),
        name: 'firestoreId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 163687397126876558),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8897024734085040376),
        name: 'parentPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2211421079852214897),
        name: 'uidTecnicoPropriedadePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4588699983721054447),
        name: 'nomeAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1283237248981818827),
        name: 'racaAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 963111509488542126),
        name: 'pesoAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5286547481113485143),
        name: 'dtNascimento',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6165444154019826004),
        name: 'touro',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6567022361569961797),
        name: 'vaca',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4017560638493064998),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8085499026171474853),
        name: 'grupoAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2833422523807156668),
        name: 'dtUltimaInseminacao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5673187711448273229),
        name: 'dtUltimoParto',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2704416727895229513),
        name: 'dtPartoPrevisto',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4315146956090850976),
        name: 'dtSecPrevista',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3885935357623816286),
        name: 'dtPrePartoPrevista',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 2492397400037686806),
        name: 'dtPP',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 8887570061563599426),
        name: 'dtDgMais',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 4320879650004770759),
        name: 'dtDgMenos',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 1863712283759063039),
        name: 'dtAborto',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 6791046750705834349),
        name: 'dtSecagem',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 1257978066216243368),
        name: 'dtUltimoPP',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 4741161288619832759),
        name: 'dtPreParto',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 2134144698228557),
        name: 'dtDescarteAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 4844891994543856782),
        name: 'dtUltimaAcao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 4546311318238891039),
        name: 'dtUltimoPartoContingencia',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 7593582241290840797),
        name: 'liberaInseminacao',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 7598900256175867623),
        name: 'nomeTouroUltimaInseminacao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 2072080928381607061),
        name: 'totalInseminacoes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 2885171771698626463),
        name: 'totalPartos',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 6742455141038620290),
        name: 'motivoDescarteAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 5901490601844779129),
        name: 'nomeBrincoConcat',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 4577014007816712352),
        name: 'idGrupoAnimal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 7055099798182102196),
        name: 'idStatusAnimal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 2355529459518998446),
        name: 'brincoAnimal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 2045653485172204371),
        name: 'brincoAnimalOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(38, 8110989046513889196),
        name: 'compararDtUltimaInseminacao',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(39, 3275362714721461566),
        name: 'dtInducaoLactacao',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(40, 1693754653417492588),
        name: 'dtDesmame',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(41, 3124050973327984315),
        name: 'lastModified',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(42, 2905846968320575639),
        name: 'lastSynced',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(43, 7962411060243664126),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(44, 7363795320818029985),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4689127300938650488),
    name: 'PendingOperationEntity',
    lastPropertyId: const obx_int.IdUid(10, 2333849240104684978),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7175872399464994013),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7716094434037669351),
        name: 'operationType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2163139422072763312),
        name: 'collectionName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2327879044025891632),
        name: 'firestoreId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5908392529602840403),
        name: 'documentPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4491331295807670492),
        name: 'dataJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8825337601313109508),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4693558825231033440),
        name: 'retryCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 39208967785409633),
        name: 'lastError',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2333849240104684978),
        name: 'priority',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4837537819797596855),
    name: 'PersonEntity',
    lastPropertyId: const obx_int.IdUid(19, 5377478473887412073),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4117632285891741346),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3809021107756887479),
        name: 'firestoreId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 6492724243196477648),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9003636381117425191),
        name: 'dtNascimento',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4401239134578850971),
        name: 'cpf',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1772986642025654553),
        name: 'uid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2125018675279425350),
        name: 'endereco',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3379921533786098284),
        name: 'cidade',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3227904793260433181),
        name: 'bairro',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2510605295371965698),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2438447566083825442),
        name: 'createdTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1182640425796722373),
        name: 'displayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7655810411144645643),
        name: 'photoUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3714772321765650800),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7166229847740549901),
        name: 'empresa',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5248982746973643861),
        name: 'tipo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 399403457913504161),
        name: 'lastModified',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 2220485181209229185),
        name: 'lastSynced',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 8480956359218143190),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 5377478473887412073),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2075314046405181166),
    name: 'ProdutorEntity',
    lastPropertyId: const obx_int.IdUid(9, 8949770742090908264),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3430924345622213945),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2201064883885220335),
        name: 'firestoreId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 7232938258253810686),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5366445235375108433),
        name: 'liberado',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9214515854633547903),
        name: 'uidTecnicoPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2995056671913094989),
        name: 'uidPersonPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6703296515637381264),
        name: 'lastModified',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7590426524941041005),
        name: 'lastSynced',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4350697707124613404),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8949770742090908264),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6656913100126291315),
    name: 'PropriedadeEntity',
    lastPropertyId: const obx_int.IdUid(16, 2240110343104043146),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6878920466618423595),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4201401286878682424),
        name: 'firestoreId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 5591589692874087129),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8043197972113219612),
        name: 'parentPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6970263119304391774),
        name: 'uidPersonProdutorPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4158649530719975810),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6076916291501506325),
        name: 'displayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3959345899071644297),
        name: 'cpf',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2876390497437155450),
        name: 'endereco',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5708248824540258571),
        name: 'cidade',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5285104315498180670),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2132563448235012808),
        name: 'diasParaDg',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 323463361263209612),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2330295810317223651),
        name: 'deletedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7283117912191522039),
        name: 'lastModified',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 608983418463563235),
        name: 'lastSynced',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 2240110343104043146),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7928747235823571726),
    name: 'SyncMetadataEntity',
    lastPropertyId: const obx_int.IdUid(7, 5965183406567634824),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8746570931669227613),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6890120061848461896),
        name: 'collectionName',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 4250504014473932116),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7532681411351054360),
        name: 'lastFullSync',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2519933706153202263),
        name: 'lastIncrementalSync',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3133922395017792864),
        name: 'initialSyncComplete',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7034471275758907053),
        name: 'recordCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5965183406567634824),
        name: 'schemaVersion',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 6395357591972958726),
    name: 'TecnicoEntity',
    lastPropertyId: const obx_int.IdUid(14, 4496123936708850230),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 407062826673902243),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5070470238017540978),
        name: 'firestoreId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 4426326080799698287),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3738148155484790974),
        name: 'uidPerson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3874397845540082237),
        name: 'liberado',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4253792479288763163),
        name: 'limiteProdutoresContratado',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8685468375955467595),
        name: 'quantidadeProdutoresCadastrados',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1207080779830634251),
        name: 'restanteLimiteProdutores',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8328879397672918696),
        name: 'limiteAnimaisContratado',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 315269411827543340),
        name: 'quantidadeAnimaisCadastrados',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8385152445757883691),
        name: 'restanteLimiteAnimais',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4259352478334575560),
        name: 'lastModified',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3171383054780161833),
        name: 'lastSynced',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1815321003954609101),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4496123936708850230),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 6395357591972958726),
    lastIndexId: const obx_int.IdUid(6, 4426326080799698287),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AnimalEntity: obx_int.EntityDefinition<AnimalEntity>(
      model: _entities[0],
      toOneRelations: (AnimalEntity object) => [],
      toManyRelations: (AnimalEntity object) => {},
      getId: (AnimalEntity object) => object.id,
      setId: (AnimalEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AnimalEntity object, fb.Builder fbb) {
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final parentPathOffset = object.parentPath == null
            ? null
            : fbb.writeString(object.parentPath!);
        final uidTecnicoPropriedadePathOffset =
            object.uidTecnicoPropriedadePath == null
            ? null
            : fbb.writeString(object.uidTecnicoPropriedadePath!);
        final nomeAnimalOffset = object.nomeAnimal == null
            ? null
            : fbb.writeString(object.nomeAnimal!);
        final racaAnimalOffset = object.racaAnimal == null
            ? null
            : fbb.writeString(object.racaAnimal!);
        final pesoAnimalOffset = object.pesoAnimal == null
            ? null
            : fbb.writeString(object.pesoAnimal!);
        final dtNascimentoOffset = object.dtNascimento == null
            ? null
            : fbb.writeString(object.dtNascimento!);
        final touroOffset = object.touro == null
            ? null
            : fbb.writeString(object.touro!);
        final vacaOffset = object.vaca == null
            ? null
            : fbb.writeString(object.vaca!);
        final statusOffset = object.status == null
            ? null
            : fbb.writeString(object.status!);
        final grupoAnimalOffset = object.grupoAnimal == null
            ? null
            : fbb.writeString(object.grupoAnimal!);
        final dtUltimaInseminacaoOffset = object.dtUltimaInseminacao == null
            ? null
            : fbb.writeString(object.dtUltimaInseminacao!);
        final dtUltimoPartoOffset = object.dtUltimoParto == null
            ? null
            : fbb.writeString(object.dtUltimoParto!);
        final dtPartoPrevistoOffset = object.dtPartoPrevisto == null
            ? null
            : fbb.writeString(object.dtPartoPrevisto!);
        final dtSecPrevistaOffset = object.dtSecPrevista == null
            ? null
            : fbb.writeString(object.dtSecPrevista!);
        final dtPrePartoPrevistaOffset = object.dtPrePartoPrevista == null
            ? null
            : fbb.writeString(object.dtPrePartoPrevista!);
        final dtPPOffset = object.dtPP == null
            ? null
            : fbb.writeString(object.dtPP!);
        final dtDgMaisOffset = object.dtDgMais == null
            ? null
            : fbb.writeString(object.dtDgMais!);
        final dtDgMenosOffset = object.dtDgMenos == null
            ? null
            : fbb.writeString(object.dtDgMenos!);
        final dtAbortoOffset = object.dtAborto == null
            ? null
            : fbb.writeString(object.dtAborto!);
        final dtSecagemOffset = object.dtSecagem == null
            ? null
            : fbb.writeString(object.dtSecagem!);
        final dtUltimoPPOffset = object.dtUltimoPP == null
            ? null
            : fbb.writeString(object.dtUltimoPP!);
        final dtPrePartoOffset = object.dtPreParto == null
            ? null
            : fbb.writeString(object.dtPreParto!);
        final dtDescarteAnimalOffset = object.dtDescarteAnimal == null
            ? null
            : fbb.writeString(object.dtDescarteAnimal!);
        final dtUltimaAcaoOffset = object.dtUltimaAcao == null
            ? null
            : fbb.writeString(object.dtUltimaAcao!);
        final dtUltimoPartoContingenciaOffset =
            object.dtUltimoPartoContingencia == null
            ? null
            : fbb.writeString(object.dtUltimoPartoContingencia!);
        final nomeTouroUltimaInseminacaoOffset =
            object.nomeTouroUltimaInseminacao == null
            ? null
            : fbb.writeString(object.nomeTouroUltimaInseminacao!);
        final motivoDescarteAnimalOffset = object.motivoDescarteAnimal == null
            ? null
            : fbb.writeString(object.motivoDescarteAnimal!);
        final nomeBrincoConcatOffset = object.nomeBrincoConcat == null
            ? null
            : fbb.writeString(object.nomeBrincoConcat!);
        fbb.startTable(45);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firestoreIdOffset);
        fbb.addOffset(2, parentPathOffset);
        fbb.addOffset(3, uidTecnicoPropriedadePathOffset);
        fbb.addOffset(4, nomeAnimalOffset);
        fbb.addOffset(5, racaAnimalOffset);
        fbb.addOffset(6, pesoAnimalOffset);
        fbb.addOffset(7, dtNascimentoOffset);
        fbb.addOffset(8, touroOffset);
        fbb.addOffset(9, vacaOffset);
        fbb.addOffset(10, statusOffset);
        fbb.addOffset(11, grupoAnimalOffset);
        fbb.addOffset(12, dtUltimaInseminacaoOffset);
        fbb.addOffset(13, dtUltimoPartoOffset);
        fbb.addOffset(14, dtPartoPrevistoOffset);
        fbb.addOffset(15, dtSecPrevistaOffset);
        fbb.addOffset(16, dtPrePartoPrevistaOffset);
        fbb.addOffset(17, dtPPOffset);
        fbb.addOffset(18, dtDgMaisOffset);
        fbb.addOffset(19, dtDgMenosOffset);
        fbb.addOffset(20, dtAbortoOffset);
        fbb.addOffset(21, dtSecagemOffset);
        fbb.addOffset(22, dtUltimoPPOffset);
        fbb.addOffset(23, dtPrePartoOffset);
        fbb.addOffset(24, dtDescarteAnimalOffset);
        fbb.addOffset(25, dtUltimaAcaoOffset);
        fbb.addOffset(26, dtUltimoPartoContingenciaOffset);
        fbb.addBool(27, object.liberaInseminacao);
        fbb.addOffset(28, nomeTouroUltimaInseminacaoOffset);
        fbb.addInt64(29, object.totalInseminacoes);
        fbb.addInt64(30, object.totalPartos);
        fbb.addOffset(31, motivoDescarteAnimalOffset);
        fbb.addOffset(32, nomeBrincoConcatOffset);
        fbb.addInt64(33, object.idGrupoAnimal);
        fbb.addInt64(34, object.idStatusAnimal);
        fbb.addInt64(35, object.brincoAnimal);
        fbb.addInt64(36, object.brincoAnimalOrder);
        fbb.addInt64(
          37,
          object.compararDtUltimaInseminacao?.millisecondsSinceEpoch,
        );
        fbb.addInt64(38, object.dtInducaoLactacao?.millisecondsSinceEpoch);
        fbb.addInt64(39, object.dtDesmame?.millisecondsSinceEpoch);
        fbb.addInt64(40, object.lastModified?.millisecondsSinceEpoch);
        fbb.addInt64(41, object.lastSynced?.millisecondsSinceEpoch);
        fbb.addBool(42, object.needsSync);
        fbb.addBool(43, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final compararDtUltimaInseminacaoValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 78);
        final dtInducaoLactacaoValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          80,
        );
        final dtDesmameValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          82,
        );
        final lastModifiedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          84,
        );
        final lastSyncedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          86,
        );
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final parentPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final uidTecnicoPropriedadePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final nomeAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final racaAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final pesoAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final dtNascimentoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final touroParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final vacaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final grupoAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final dtUltimaInseminacaoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final dtUltimoPartoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final dtPartoPrevistoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final dtSecPrevistaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final dtPrePartoPrevistaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final dtPPParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final dtDgMaisParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final dtDgMenosParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final dtAbortoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 44);
        final dtSecagemParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final dtUltimoPPParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final dtPrePartoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final dtDescarteAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 52);
        final dtUltimaAcaoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 54);
        final dtUltimoPartoContingenciaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 56);
        final liberaInseminacaoParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          58,
          false,
        );
        final nomeTouroUltimaInseminacaoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 60);
        final totalInseminacoesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          62,
          0,
        );
        final totalPartosParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          64,
          0,
        );
        final motivoDescarteAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 66);
        final nomeBrincoConcatParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 68);
        final idGrupoAnimalParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          70,
          0,
        );
        final idStatusAnimalParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          72,
          0,
        );
        final brincoAnimalParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          74,
          0,
        );
        final brincoAnimalOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          76,
          0,
        );
        final compararDtUltimaInseminacaoParam =
            compararDtUltimaInseminacaoValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(
                compararDtUltimaInseminacaoValue,
              );
        final dtInducaoLactacaoParam = dtInducaoLactacaoValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dtInducaoLactacaoValue);
        final dtDesmameParam = dtDesmameValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dtDesmameValue);
        final lastModifiedParam = lastModifiedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastModifiedValue);
        final lastSyncedParam = lastSyncedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          88,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          90,
          false,
        );
        final object = AnimalEntity(
          firestoreId: firestoreIdParam,
          parentPath: parentPathParam,
          uidTecnicoPropriedadePath: uidTecnicoPropriedadePathParam,
          nomeAnimal: nomeAnimalParam,
          racaAnimal: racaAnimalParam,
          pesoAnimal: pesoAnimalParam,
          dtNascimento: dtNascimentoParam,
          touro: touroParam,
          vaca: vacaParam,
          status: statusParam,
          grupoAnimal: grupoAnimalParam,
          dtUltimaInseminacao: dtUltimaInseminacaoParam,
          dtUltimoParto: dtUltimoPartoParam,
          dtPartoPrevisto: dtPartoPrevistoParam,
          dtSecPrevista: dtSecPrevistaParam,
          dtPrePartoPrevista: dtPrePartoPrevistaParam,
          dtPP: dtPPParam,
          dtDgMais: dtDgMaisParam,
          dtDgMenos: dtDgMenosParam,
          dtAborto: dtAbortoParam,
          dtSecagem: dtSecagemParam,
          dtUltimoPP: dtUltimoPPParam,
          dtPreParto: dtPrePartoParam,
          dtDescarteAnimal: dtDescarteAnimalParam,
          dtUltimaAcao: dtUltimaAcaoParam,
          dtUltimoPartoContingencia: dtUltimoPartoContingenciaParam,
          liberaInseminacao: liberaInseminacaoParam,
          nomeTouroUltimaInseminacao: nomeTouroUltimaInseminacaoParam,
          totalInseminacoes: totalInseminacoesParam,
          totalPartos: totalPartosParam,
          motivoDescarteAnimal: motivoDescarteAnimalParam,
          nomeBrincoConcat: nomeBrincoConcatParam,
          idGrupoAnimal: idGrupoAnimalParam,
          idStatusAnimal: idStatusAnimalParam,
          brincoAnimal: brincoAnimalParam,
          brincoAnimalOrder: brincoAnimalOrderParam,
          compararDtUltimaInseminacao: compararDtUltimaInseminacaoParam,
          dtInducaoLactacao: dtInducaoLactacaoParam,
          dtDesmame: dtDesmameParam,
          lastModified: lastModifiedParam,
          lastSynced: lastSyncedParam,
          needsSync: needsSyncParam,
          isDeleted: isDeletedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    PendingOperationEntity: obx_int.EntityDefinition<PendingOperationEntity>(
      model: _entities[1],
      toOneRelations: (PendingOperationEntity object) => [],
      toManyRelations: (PendingOperationEntity object) => {},
      getId: (PendingOperationEntity object) => object.id,
      setId: (PendingOperationEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PendingOperationEntity object, fb.Builder fbb) {
        final operationTypeOffset = object.operationType == null
            ? null
            : fbb.writeString(object.operationType!);
        final collectionNameOffset = object.collectionName == null
            ? null
            : fbb.writeString(object.collectionName!);
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final documentPathOffset = object.documentPath == null
            ? null
            : fbb.writeString(object.documentPath!);
        final dataJsonOffset = object.dataJson == null
            ? null
            : fbb.writeString(object.dataJson!);
        final lastErrorOffset = object.lastError == null
            ? null
            : fbb.writeString(object.lastError!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, operationTypeOffset);
        fbb.addOffset(2, collectionNameOffset);
        fbb.addOffset(3, firestoreIdOffset);
        fbb.addOffset(4, documentPathOffset);
        fbb.addOffset(5, dataJsonOffset);
        fbb.addInt64(6, object.createdAt?.millisecondsSinceEpoch);
        fbb.addInt64(7, object.retryCount);
        fbb.addOffset(8, lastErrorOffset);
        fbb.addInt64(9, object.priority);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final operationTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final collectionNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final documentPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final dataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final retryCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final lastErrorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final priorityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final object = PendingOperationEntity(
          operationType: operationTypeParam,
          collectionName: collectionNameParam,
          firestoreId: firestoreIdParam,
          documentPath: documentPathParam,
          dataJson: dataJsonParam,
          createdAt: createdAtParam,
          retryCount: retryCountParam,
          lastError: lastErrorParam,
          priority: priorityParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    PersonEntity: obx_int.EntityDefinition<PersonEntity>(
      model: _entities[2],
      toOneRelations: (PersonEntity object) => [],
      toManyRelations: (PersonEntity object) => {},
      getId: (PersonEntity object) => object.id,
      setId: (PersonEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PersonEntity object, fb.Builder fbb) {
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final dtNascimentoOffset = object.dtNascimento == null
            ? null
            : fbb.writeString(object.dtNascimento!);
        final cpfOffset = object.cpf == null
            ? null
            : fbb.writeString(object.cpf!);
        final uidOffset = object.uid == null
            ? null
            : fbb.writeString(object.uid!);
        final enderecoOffset = object.endereco == null
            ? null
            : fbb.writeString(object.endereco!);
        final cidadeOffset = object.cidade == null
            ? null
            : fbb.writeString(object.cidade!);
        final bairroOffset = object.bairro == null
            ? null
            : fbb.writeString(object.bairro!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final displayNameOffset = object.displayName == null
            ? null
            : fbb.writeString(object.displayName!);
        final photoUrlOffset = object.photoUrl == null
            ? null
            : fbb.writeString(object.photoUrl!);
        final phoneNumberOffset = object.phoneNumber == null
            ? null
            : fbb.writeString(object.phoneNumber!);
        final empresaOffset = object.empresa == null
            ? null
            : fbb.writeString(object.empresa!);
        final tipoOffset = object.tipo == null
            ? null
            : fbb.writeString(object.tipo!);
        fbb.startTable(20);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firestoreIdOffset);
        fbb.addOffset(2, dtNascimentoOffset);
        fbb.addOffset(3, cpfOffset);
        fbb.addOffset(4, uidOffset);
        fbb.addOffset(5, enderecoOffset);
        fbb.addOffset(6, cidadeOffset);
        fbb.addOffset(7, bairroOffset);
        fbb.addOffset(8, emailOffset);
        fbb.addInt64(9, object.createdTime?.millisecondsSinceEpoch);
        fbb.addOffset(10, displayNameOffset);
        fbb.addOffset(11, photoUrlOffset);
        fbb.addOffset(12, phoneNumberOffset);
        fbb.addOffset(13, empresaOffset);
        fbb.addOffset(14, tipoOffset);
        fbb.addInt64(15, object.lastModified?.millisecondsSinceEpoch);
        fbb.addInt64(16, object.lastSynced?.millisecondsSinceEpoch);
        fbb.addBool(17, object.needsSync);
        fbb.addBool(18, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final lastModifiedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final lastSyncedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          36,
        );
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final dtNascimentoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final cpfParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final enderecoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final cidadeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final bairroParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final createdTimeParam = createdTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdTimeValue);
        final displayNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final photoUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final empresaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final tipoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final lastModifiedParam = lastModifiedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastModifiedValue);
        final lastSyncedParam = lastSyncedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          38,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          40,
          false,
        );
        final object = PersonEntity(
          firestoreId: firestoreIdParam,
          dtNascimento: dtNascimentoParam,
          cpf: cpfParam,
          uid: uidParam,
          endereco: enderecoParam,
          cidade: cidadeParam,
          bairro: bairroParam,
          email: emailParam,
          createdTime: createdTimeParam,
          displayName: displayNameParam,
          photoUrl: photoUrlParam,
          phoneNumber: phoneNumberParam,
          empresa: empresaParam,
          tipo: tipoParam,
          lastModified: lastModifiedParam,
          lastSynced: lastSyncedParam,
          needsSync: needsSyncParam,
          isDeleted: isDeletedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ProdutorEntity: obx_int.EntityDefinition<ProdutorEntity>(
      model: _entities[3],
      toOneRelations: (ProdutorEntity object) => [],
      toManyRelations: (ProdutorEntity object) => {},
      getId: (ProdutorEntity object) => object.id,
      setId: (ProdutorEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ProdutorEntity object, fb.Builder fbb) {
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final uidTecnicoPathOffset = object.uidTecnicoPath == null
            ? null
            : fbb.writeString(object.uidTecnicoPath!);
        final uidPersonPathOffset = object.uidPersonPath == null
            ? null
            : fbb.writeString(object.uidPersonPath!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firestoreIdOffset);
        fbb.addBool(2, object.liberado);
        fbb.addOffset(3, uidTecnicoPathOffset);
        fbb.addOffset(4, uidPersonPathOffset);
        fbb.addInt64(5, object.lastModified?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.lastSynced?.millisecondsSinceEpoch);
        fbb.addBool(7, object.needsSync);
        fbb.addBool(8, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastModifiedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final lastSyncedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final liberadoParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final uidTecnicoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final uidPersonPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final lastModifiedParam = lastModifiedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastModifiedValue);
        final lastSyncedParam = lastSyncedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = ProdutorEntity(
          firestoreId: firestoreIdParam,
          liberado: liberadoParam,
          uidTecnicoPath: uidTecnicoPathParam,
          uidPersonPath: uidPersonPathParam,
          lastModified: lastModifiedParam,
          lastSynced: lastSyncedParam,
          needsSync: needsSyncParam,
          isDeleted: isDeletedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    PropriedadeEntity: obx_int.EntityDefinition<PropriedadeEntity>(
      model: _entities[4],
      toOneRelations: (PropriedadeEntity object) => [],
      toManyRelations: (PropriedadeEntity object) => {},
      getId: (PropriedadeEntity object) => object.id,
      setId: (PropriedadeEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PropriedadeEntity object, fb.Builder fbb) {
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final parentPathOffset = object.parentPath == null
            ? null
            : fbb.writeString(object.parentPath!);
        final uidPersonProdutorPathOffset = object.uidPersonProdutorPath == null
            ? null
            : fbb.writeString(object.uidPersonProdutorPath!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final displayNameOffset = object.displayName == null
            ? null
            : fbb.writeString(object.displayName!);
        final cpfOffset = object.cpf == null
            ? null
            : fbb.writeString(object.cpf!);
        final enderecoOffset = object.endereco == null
            ? null
            : fbb.writeString(object.endereco!);
        final cidadeOffset = object.cidade == null
            ? null
            : fbb.writeString(object.cidade!);
        final phoneNumberOffset = object.phoneNumber == null
            ? null
            : fbb.writeString(object.phoneNumber!);
        final diasParaDgOffset = object.diasParaDg == null
            ? null
            : fbb.writeString(object.diasParaDg!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firestoreIdOffset);
        fbb.addOffset(2, parentPathOffset);
        fbb.addOffset(3, uidPersonProdutorPathOffset);
        fbb.addOffset(4, emailOffset);
        fbb.addOffset(5, displayNameOffset);
        fbb.addOffset(6, cpfOffset);
        fbb.addOffset(7, enderecoOffset);
        fbb.addOffset(8, cidadeOffset);
        fbb.addOffset(9, phoneNumberOffset);
        fbb.addOffset(10, diasParaDgOffset);
        fbb.addBool(11, object.isDeleted);
        fbb.addInt64(12, object.deletedAt?.millisecondsSinceEpoch);
        fbb.addInt64(13, object.lastModified?.millisecondsSinceEpoch);
        fbb.addInt64(14, object.lastSynced?.millisecondsSinceEpoch);
        fbb.addBool(15, object.needsSync);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deletedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final lastModifiedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final lastSyncedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final parentPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final uidPersonProdutorPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final displayNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final cpfParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final enderecoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final cidadeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final diasParaDgParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final deletedAtParam = deletedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(deletedAtValue);
        final lastModifiedParam = lastModifiedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastModifiedValue);
        final lastSyncedParam = lastSyncedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          34,
          false,
        );
        final object = PropriedadeEntity(
          firestoreId: firestoreIdParam,
          parentPath: parentPathParam,
          uidPersonProdutorPath: uidPersonProdutorPathParam,
          email: emailParam,
          displayName: displayNameParam,
          cpf: cpfParam,
          endereco: enderecoParam,
          cidade: cidadeParam,
          phoneNumber: phoneNumberParam,
          diasParaDg: diasParaDgParam,
          isDeleted: isDeletedParam,
          deletedAt: deletedAtParam,
          lastModified: lastModifiedParam,
          lastSynced: lastSyncedParam,
          needsSync: needsSyncParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    SyncMetadataEntity: obx_int.EntityDefinition<SyncMetadataEntity>(
      model: _entities[5],
      toOneRelations: (SyncMetadataEntity object) => [],
      toManyRelations: (SyncMetadataEntity object) => {},
      getId: (SyncMetadataEntity object) => object.id,
      setId: (SyncMetadataEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SyncMetadataEntity object, fb.Builder fbb) {
        final collectionNameOffset = object.collectionName == null
            ? null
            : fbb.writeString(object.collectionName!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, collectionNameOffset);
        fbb.addInt64(2, object.lastFullSync?.millisecondsSinceEpoch);
        fbb.addInt64(3, object.lastIncrementalSync?.millisecondsSinceEpoch);
        fbb.addBool(4, object.initialSyncComplete);
        fbb.addInt64(5, object.recordCount);
        fbb.addInt64(6, object.schemaVersion);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastFullSyncValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final lastIncrementalSyncValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 10);
        final collectionNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final lastFullSyncParam = lastFullSyncValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastFullSyncValue);
        final lastIncrementalSyncParam = lastIncrementalSyncValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastIncrementalSyncValue);
        final initialSyncCompleteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final recordCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final schemaVersionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = SyncMetadataEntity(
          collectionName: collectionNameParam,
          lastFullSync: lastFullSyncParam,
          lastIncrementalSync: lastIncrementalSyncParam,
          initialSyncComplete: initialSyncCompleteParam,
          recordCount: recordCountParam,
          schemaVersion: schemaVersionParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    TecnicoEntity: obx_int.EntityDefinition<TecnicoEntity>(
      model: _entities[6],
      toOneRelations: (TecnicoEntity object) => [],
      toManyRelations: (TecnicoEntity object) => {},
      getId: (TecnicoEntity object) => object.id,
      setId: (TecnicoEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TecnicoEntity object, fb.Builder fbb) {
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final uidPersonOffset = object.uidPerson == null
            ? null
            : fbb.writeString(object.uidPerson!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firestoreIdOffset);
        fbb.addOffset(2, uidPersonOffset);
        fbb.addBool(3, object.liberado);
        fbb.addInt64(4, object.limiteProdutoresContratado);
        fbb.addInt64(5, object.quantidadeProdutoresCadastrados);
        fbb.addInt64(6, object.restanteLimiteProdutores);
        fbb.addInt64(7, object.limiteAnimaisContratado);
        fbb.addInt64(8, object.quantidadeAnimaisCadastrados);
        fbb.addInt64(9, object.restanteLimiteAnimais);
        fbb.addInt64(10, object.lastModified?.millisecondsSinceEpoch);
        fbb.addInt64(11, object.lastSynced?.millisecondsSinceEpoch);
        fbb.addBool(12, object.needsSync);
        fbb.addBool(13, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastModifiedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final lastSyncedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final uidPersonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final liberadoParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final limiteProdutoresContratadoParam = const fb.Int64Reader()
            .vTableGet(buffer, rootOffset, 12, 0);
        final quantidadeProdutoresCadastradosParam = const fb.Int64Reader()
            .vTableGet(buffer, rootOffset, 14, 0);
        final restanteLimiteProdutoresParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final limiteAnimaisContratadoParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final quantidadeAnimaisCadastradosParam = const fb.Int64Reader()
            .vTableGet(buffer, rootOffset, 20, 0);
        final restanteLimiteAnimaisParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final lastModifiedParam = lastModifiedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastModifiedValue);
        final lastSyncedParam = lastSyncedValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final object = TecnicoEntity(
          firestoreId: firestoreIdParam,
          uidPerson: uidPersonParam,
          liberado: liberadoParam,
          limiteProdutoresContratado: limiteProdutoresContratadoParam,
          quantidadeProdutoresCadastrados: quantidadeProdutoresCadastradosParam,
          restanteLimiteProdutores: restanteLimiteProdutoresParam,
          limiteAnimaisContratado: limiteAnimaisContratadoParam,
          quantidadeAnimaisCadastrados: quantidadeAnimaisCadastradosParam,
          restanteLimiteAnimais: restanteLimiteAnimaisParam,
          lastModified: lastModifiedParam,
          lastSynced: lastSyncedParam,
          needsSync: needsSyncParam,
          isDeleted: isDeletedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AnimalEntity] entity fields to define ObjectBox queries.
class AnimalEntity_ {
  /// See [AnimalEntity.id].
  static final id = obx.QueryIntegerProperty<AnimalEntity>(
    _entities[0].properties[0],
  );

  /// See [AnimalEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[1],
  );

  /// See [AnimalEntity.parentPath].
  static final parentPath = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[2],
  );

  /// See [AnimalEntity.uidTecnicoPropriedadePath].
  static final uidTecnicoPropriedadePath =
      obx.QueryStringProperty<AnimalEntity>(_entities[0].properties[3]);

  /// See [AnimalEntity.nomeAnimal].
  static final nomeAnimal = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[4],
  );

  /// See [AnimalEntity.racaAnimal].
  static final racaAnimal = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[5],
  );

  /// See [AnimalEntity.pesoAnimal].
  static final pesoAnimal = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[6],
  );

  /// See [AnimalEntity.dtNascimento].
  static final dtNascimento = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[7],
  );

  /// See [AnimalEntity.touro].
  static final touro = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[8],
  );

  /// See [AnimalEntity.vaca].
  static final vaca = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[9],
  );

  /// See [AnimalEntity.status].
  static final status = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[10],
  );

  /// See [AnimalEntity.grupoAnimal].
  static final grupoAnimal = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[11],
  );

  /// See [AnimalEntity.dtUltimaInseminacao].
  static final dtUltimaInseminacao = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[12],
  );

  /// See [AnimalEntity.dtUltimoParto].
  static final dtUltimoParto = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[13],
  );

  /// See [AnimalEntity.dtPartoPrevisto].
  static final dtPartoPrevisto = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[14],
  );

  /// See [AnimalEntity.dtSecPrevista].
  static final dtSecPrevista = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[15],
  );

  /// See [AnimalEntity.dtPrePartoPrevista].
  static final dtPrePartoPrevista = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[16],
  );

  /// See [AnimalEntity.dtPP].
  static final dtPP = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[17],
  );

  /// See [AnimalEntity.dtDgMais].
  static final dtDgMais = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[18],
  );

  /// See [AnimalEntity.dtDgMenos].
  static final dtDgMenos = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[19],
  );

  /// See [AnimalEntity.dtAborto].
  static final dtAborto = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[20],
  );

  /// See [AnimalEntity.dtSecagem].
  static final dtSecagem = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[21],
  );

  /// See [AnimalEntity.dtUltimoPP].
  static final dtUltimoPP = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[22],
  );

  /// See [AnimalEntity.dtPreParto].
  static final dtPreParto = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[23],
  );

  /// See [AnimalEntity.dtDescarteAnimal].
  static final dtDescarteAnimal = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[24],
  );

  /// See [AnimalEntity.dtUltimaAcao].
  static final dtUltimaAcao = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[25],
  );

  /// See [AnimalEntity.dtUltimoPartoContingencia].
  static final dtUltimoPartoContingencia =
      obx.QueryStringProperty<AnimalEntity>(_entities[0].properties[26]);

  /// See [AnimalEntity.liberaInseminacao].
  static final liberaInseminacao = obx.QueryBooleanProperty<AnimalEntity>(
    _entities[0].properties[27],
  );

  /// See [AnimalEntity.nomeTouroUltimaInseminacao].
  static final nomeTouroUltimaInseminacao =
      obx.QueryStringProperty<AnimalEntity>(_entities[0].properties[28]);

  /// See [AnimalEntity.totalInseminacoes].
  static final totalInseminacoes = obx.QueryIntegerProperty<AnimalEntity>(
    _entities[0].properties[29],
  );

  /// See [AnimalEntity.totalPartos].
  static final totalPartos = obx.QueryIntegerProperty<AnimalEntity>(
    _entities[0].properties[30],
  );

  /// See [AnimalEntity.motivoDescarteAnimal].
  static final motivoDescarteAnimal = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[31],
  );

  /// See [AnimalEntity.nomeBrincoConcat].
  static final nomeBrincoConcat = obx.QueryStringProperty<AnimalEntity>(
    _entities[0].properties[32],
  );

  /// See [AnimalEntity.idGrupoAnimal].
  static final idGrupoAnimal = obx.QueryIntegerProperty<AnimalEntity>(
    _entities[0].properties[33],
  );

  /// See [AnimalEntity.idStatusAnimal].
  static final idStatusAnimal = obx.QueryIntegerProperty<AnimalEntity>(
    _entities[0].properties[34],
  );

  /// See [AnimalEntity.brincoAnimal].
  static final brincoAnimal = obx.QueryIntegerProperty<AnimalEntity>(
    _entities[0].properties[35],
  );

  /// See [AnimalEntity.brincoAnimalOrder].
  static final brincoAnimalOrder = obx.QueryIntegerProperty<AnimalEntity>(
    _entities[0].properties[36],
  );

  /// See [AnimalEntity.compararDtUltimaInseminacao].
  static final compararDtUltimaInseminacao =
      obx.QueryDateProperty<AnimalEntity>(_entities[0].properties[37]);

  /// See [AnimalEntity.dtInducaoLactacao].
  static final dtInducaoLactacao = obx.QueryDateProperty<AnimalEntity>(
    _entities[0].properties[38],
  );

  /// See [AnimalEntity.dtDesmame].
  static final dtDesmame = obx.QueryDateProperty<AnimalEntity>(
    _entities[0].properties[39],
  );

  /// See [AnimalEntity.lastModified].
  static final lastModified = obx.QueryDateProperty<AnimalEntity>(
    _entities[0].properties[40],
  );

  /// See [AnimalEntity.lastSynced].
  static final lastSynced = obx.QueryDateProperty<AnimalEntity>(
    _entities[0].properties[41],
  );

  /// See [AnimalEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<AnimalEntity>(
    _entities[0].properties[42],
  );

  /// See [AnimalEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<AnimalEntity>(
    _entities[0].properties[43],
  );
}

/// [PendingOperationEntity] entity fields to define ObjectBox queries.
class PendingOperationEntity_ {
  /// See [PendingOperationEntity.id].
  static final id = obx.QueryIntegerProperty<PendingOperationEntity>(
    _entities[1].properties[0],
  );

  /// See [PendingOperationEntity.operationType].
  static final operationType = obx.QueryStringProperty<PendingOperationEntity>(
    _entities[1].properties[1],
  );

  /// See [PendingOperationEntity.collectionName].
  static final collectionName = obx.QueryStringProperty<PendingOperationEntity>(
    _entities[1].properties[2],
  );

  /// See [PendingOperationEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<PendingOperationEntity>(
    _entities[1].properties[3],
  );

  /// See [PendingOperationEntity.documentPath].
  static final documentPath = obx.QueryStringProperty<PendingOperationEntity>(
    _entities[1].properties[4],
  );

  /// See [PendingOperationEntity.dataJson].
  static final dataJson = obx.QueryStringProperty<PendingOperationEntity>(
    _entities[1].properties[5],
  );

  /// See [PendingOperationEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<PendingOperationEntity>(
    _entities[1].properties[6],
  );

  /// See [PendingOperationEntity.retryCount].
  static final retryCount = obx.QueryIntegerProperty<PendingOperationEntity>(
    _entities[1].properties[7],
  );

  /// See [PendingOperationEntity.lastError].
  static final lastError = obx.QueryStringProperty<PendingOperationEntity>(
    _entities[1].properties[8],
  );

  /// See [PendingOperationEntity.priority].
  static final priority = obx.QueryIntegerProperty<PendingOperationEntity>(
    _entities[1].properties[9],
  );
}

/// [PersonEntity] entity fields to define ObjectBox queries.
class PersonEntity_ {
  /// See [PersonEntity.id].
  static final id = obx.QueryIntegerProperty<PersonEntity>(
    _entities[2].properties[0],
  );

  /// See [PersonEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[1],
  );

  /// See [PersonEntity.dtNascimento].
  static final dtNascimento = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[2],
  );

  /// See [PersonEntity.cpf].
  static final cpf = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[3],
  );

  /// See [PersonEntity.uid].
  static final uid = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[4],
  );

  /// See [PersonEntity.endereco].
  static final endereco = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[5],
  );

  /// See [PersonEntity.cidade].
  static final cidade = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[6],
  );

  /// See [PersonEntity.bairro].
  static final bairro = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[7],
  );

  /// See [PersonEntity.email].
  static final email = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[8],
  );

  /// See [PersonEntity.createdTime].
  static final createdTime = obx.QueryDateProperty<PersonEntity>(
    _entities[2].properties[9],
  );

  /// See [PersonEntity.displayName].
  static final displayName = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[10],
  );

  /// See [PersonEntity.photoUrl].
  static final photoUrl = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[11],
  );

  /// See [PersonEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[12],
  );

  /// See [PersonEntity.empresa].
  static final empresa = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[13],
  );

  /// See [PersonEntity.tipo].
  static final tipo = obx.QueryStringProperty<PersonEntity>(
    _entities[2].properties[14],
  );

  /// See [PersonEntity.lastModified].
  static final lastModified = obx.QueryDateProperty<PersonEntity>(
    _entities[2].properties[15],
  );

  /// See [PersonEntity.lastSynced].
  static final lastSynced = obx.QueryDateProperty<PersonEntity>(
    _entities[2].properties[16],
  );

  /// See [PersonEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<PersonEntity>(
    _entities[2].properties[17],
  );

  /// See [PersonEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<PersonEntity>(
    _entities[2].properties[18],
  );
}

/// [ProdutorEntity] entity fields to define ObjectBox queries.
class ProdutorEntity_ {
  /// See [ProdutorEntity.id].
  static final id = obx.QueryIntegerProperty<ProdutorEntity>(
    _entities[3].properties[0],
  );

  /// See [ProdutorEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<ProdutorEntity>(
    _entities[3].properties[1],
  );

  /// See [ProdutorEntity.liberado].
  static final liberado = obx.QueryBooleanProperty<ProdutorEntity>(
    _entities[3].properties[2],
  );

  /// See [ProdutorEntity.uidTecnicoPath].
  static final uidTecnicoPath = obx.QueryStringProperty<ProdutorEntity>(
    _entities[3].properties[3],
  );

  /// See [ProdutorEntity.uidPersonPath].
  static final uidPersonPath = obx.QueryStringProperty<ProdutorEntity>(
    _entities[3].properties[4],
  );

  /// See [ProdutorEntity.lastModified].
  static final lastModified = obx.QueryDateProperty<ProdutorEntity>(
    _entities[3].properties[5],
  );

  /// See [ProdutorEntity.lastSynced].
  static final lastSynced = obx.QueryDateProperty<ProdutorEntity>(
    _entities[3].properties[6],
  );

  /// See [ProdutorEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<ProdutorEntity>(
    _entities[3].properties[7],
  );

  /// See [ProdutorEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<ProdutorEntity>(
    _entities[3].properties[8],
  );
}

/// [PropriedadeEntity] entity fields to define ObjectBox queries.
class PropriedadeEntity_ {
  /// See [PropriedadeEntity.id].
  static final id = obx.QueryIntegerProperty<PropriedadeEntity>(
    _entities[4].properties[0],
  );

  /// See [PropriedadeEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<PropriedadeEntity>(
    _entities[4].properties[1],
  );

  /// See [PropriedadeEntity.parentPath].
  static final parentPath = obx.QueryStringProperty<PropriedadeEntity>(
    _entities[4].properties[2],
  );

  /// See [PropriedadeEntity.uidPersonProdutorPath].
  static final uidPersonProdutorPath =
      obx.QueryStringProperty<PropriedadeEntity>(_entities[4].properties[3]);

  /// See [PropriedadeEntity.email].
  static final email = obx.QueryStringProperty<PropriedadeEntity>(
    _entities[4].properties[4],
  );

  /// See [PropriedadeEntity.displayName].
  static final displayName = obx.QueryStringProperty<PropriedadeEntity>(
    _entities[4].properties[5],
  );

  /// See [PropriedadeEntity.cpf].
  static final cpf = obx.QueryStringProperty<PropriedadeEntity>(
    _entities[4].properties[6],
  );

  /// See [PropriedadeEntity.endereco].
  static final endereco = obx.QueryStringProperty<PropriedadeEntity>(
    _entities[4].properties[7],
  );

  /// See [PropriedadeEntity.cidade].
  static final cidade = obx.QueryStringProperty<PropriedadeEntity>(
    _entities[4].properties[8],
  );

  /// See [PropriedadeEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<PropriedadeEntity>(
    _entities[4].properties[9],
  );

  /// See [PropriedadeEntity.diasParaDg].
  static final diasParaDg = obx.QueryStringProperty<PropriedadeEntity>(
    _entities[4].properties[10],
  );

  /// See [PropriedadeEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<PropriedadeEntity>(
    _entities[4].properties[11],
  );

  /// See [PropriedadeEntity.deletedAt].
  static final deletedAt = obx.QueryDateProperty<PropriedadeEntity>(
    _entities[4].properties[12],
  );

  /// See [PropriedadeEntity.lastModified].
  static final lastModified = obx.QueryDateProperty<PropriedadeEntity>(
    _entities[4].properties[13],
  );

  /// See [PropriedadeEntity.lastSynced].
  static final lastSynced = obx.QueryDateProperty<PropriedadeEntity>(
    _entities[4].properties[14],
  );

  /// See [PropriedadeEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<PropriedadeEntity>(
    _entities[4].properties[15],
  );
}

/// [SyncMetadataEntity] entity fields to define ObjectBox queries.
class SyncMetadataEntity_ {
  /// See [SyncMetadataEntity.id].
  static final id = obx.QueryIntegerProperty<SyncMetadataEntity>(
    _entities[5].properties[0],
  );

  /// See [SyncMetadataEntity.collectionName].
  static final collectionName = obx.QueryStringProperty<SyncMetadataEntity>(
    _entities[5].properties[1],
  );

  /// See [SyncMetadataEntity.lastFullSync].
  static final lastFullSync = obx.QueryDateProperty<SyncMetadataEntity>(
    _entities[5].properties[2],
  );

  /// See [SyncMetadataEntity.lastIncrementalSync].
  static final lastIncrementalSync = obx.QueryDateProperty<SyncMetadataEntity>(
    _entities[5].properties[3],
  );

  /// See [SyncMetadataEntity.initialSyncComplete].
  static final initialSyncComplete =
      obx.QueryBooleanProperty<SyncMetadataEntity>(_entities[5].properties[4]);

  /// See [SyncMetadataEntity.recordCount].
  static final recordCount = obx.QueryIntegerProperty<SyncMetadataEntity>(
    _entities[5].properties[5],
  );

  /// See [SyncMetadataEntity.schemaVersion].
  static final schemaVersion = obx.QueryIntegerProperty<SyncMetadataEntity>(
    _entities[5].properties[6],
  );
}

/// [TecnicoEntity] entity fields to define ObjectBox queries.
class TecnicoEntity_ {
  /// See [TecnicoEntity.id].
  static final id = obx.QueryIntegerProperty<TecnicoEntity>(
    _entities[6].properties[0],
  );

  /// See [TecnicoEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<TecnicoEntity>(
    _entities[6].properties[1],
  );

  /// See [TecnicoEntity.uidPerson].
  static final uidPerson = obx.QueryStringProperty<TecnicoEntity>(
    _entities[6].properties[2],
  );

  /// See [TecnicoEntity.liberado].
  static final liberado = obx.QueryBooleanProperty<TecnicoEntity>(
    _entities[6].properties[3],
  );

  /// See [TecnicoEntity.limiteProdutoresContratado].
  static final limiteProdutoresContratado =
      obx.QueryIntegerProperty<TecnicoEntity>(_entities[6].properties[4]);

  /// See [TecnicoEntity.quantidadeProdutoresCadastrados].
  static final quantidadeProdutoresCadastrados =
      obx.QueryIntegerProperty<TecnicoEntity>(_entities[6].properties[5]);

  /// See [TecnicoEntity.restanteLimiteProdutores].
  static final restanteLimiteProdutores =
      obx.QueryIntegerProperty<TecnicoEntity>(_entities[6].properties[6]);

  /// See [TecnicoEntity.limiteAnimaisContratado].
  static final limiteAnimaisContratado =
      obx.QueryIntegerProperty<TecnicoEntity>(_entities[6].properties[7]);

  /// See [TecnicoEntity.quantidadeAnimaisCadastrados].
  static final quantidadeAnimaisCadastrados =
      obx.QueryIntegerProperty<TecnicoEntity>(_entities[6].properties[8]);

  /// See [TecnicoEntity.restanteLimiteAnimais].
  static final restanteLimiteAnimais = obx.QueryIntegerProperty<TecnicoEntity>(
    _entities[6].properties[9],
  );

  /// See [TecnicoEntity.lastModified].
  static final lastModified = obx.QueryDateProperty<TecnicoEntity>(
    _entities[6].properties[10],
  );

  /// See [TecnicoEntity.lastSynced].
  static final lastSynced = obx.QueryDateProperty<TecnicoEntity>(
    _entities[6].properties[11],
  );

  /// See [TecnicoEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<TecnicoEntity>(
    _entities[6].properties[12],
  );

  /// See [TecnicoEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<TecnicoEntity>(
    _entities[6].properties[13],
  );
}
