// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/local/animais_produtores_entity.dart';
import 'data/local/person_entity.dart';
import 'data/local/produtor_entity.dart';
import 'data/local/propriedades_entity.dart';
import 'data/local/tecnico_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 180906556727129501),
    name: 'PersonEntity',
    lastPropertyId: const obx_int.IdUid(18, 3661234114971434811),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5657844095763966854),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2735568098922541903),
        name: 'firestoreId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5655651584000789575),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3445607830259511833),
        name: 'dtNascimento',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 970002778285985180),
        name: 'cpf',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3247592818841006165),
        name: 'uid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 418515857538776401),
        name: 'endereco',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2660447208534927989),
        name: 'cidade',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4492954896025654167),
        name: 'bairro',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 14715677268288445),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1385459794210831243),
        name: 'createdTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7416180495830413332),
        name: 'displayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1762654788221122945),
        name: 'photoUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8826928949482014167),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4773276145148120215),
        name: 'empresa',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6476874405523206361),
        name: 'tipo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1452243607627700482),
        name: 'lastSyncedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 302978542458002705),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3661234114971434811),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 595553455940109024),
    name: 'AnimaisProdutoresEntity',
    lastPropertyId: const obx_int.IdUid(43, 8367300470122071856),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 39886813013127930),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7517289602649658212),
        name: 'firestoreId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 8367678798005850592),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6191536270418342575),
        name: 'uidTecnicoPropriedade',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8322371403843388673),
        name: 'nomeAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3186748005743992369),
        name: 'racaAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 594155586445911785),
        name: 'pesoAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5842961668821313946),
        name: 'dtNascimento',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 693116710403080685),
        name: 'touro',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9193800850951811825),
        name: 'vaca',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8711794578390186060),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7369476867544354550),
        name: 'grupoAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3704176894154981036),
        name: 'dtUltimaInseminacao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5126652037055183830),
        name: 'dtUltimoParto',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2087679535443345507),
        name: 'liberaInseminacao',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 701198097101290854),
        name: 'dtPartoPrevisto',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 6738291765463805170),
        name: 'dtSecPrevista',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6639569173732875405),
        name: 'dtPrePartoPrevista',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7565501307617547649),
        name: 'dtPP',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 1205243609567869568),
        name: 'dtDgMais',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 4522973885082378360),
        name: 'dtDgMenos',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 8348661424624084903),
        name: 'dtAborto',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 19597489653459185),
        name: 'dtSecagem',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 388362232290604521),
        name: 'dtUltimoPP',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 6187625297554525995),
        name: 'nomeTouroUltimaInseminacao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 5638704682078806855),
        name: 'totalInseminacoes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 6414971957091371235),
        name: 'totalPartos',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 6958916098536943767),
        name: 'dtPreParto',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 7916703446005294756),
        name: 'motivoDescarteAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 5769414284478091169),
        name: 'dtDescarteAnimal',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 2759483759121080150),
        name: 'dtUltimaAcao',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 9065469946421063040),
        name: 'compararDtUltimaInseminacao',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 2786830048631976571),
        name: 'nomeBrincoConcat',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 5022228237032479809),
        name: 'idGrupoAnimal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 6382706188716376171),
        name: 'dtUltimoPartoContingencia',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 4200182571542167950),
        name: 'idStatusAnimal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 3828660514979795670),
        name: 'dtInducaoLactacao',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 1663339009136588346),
        name: 'dtDesmame',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(38, 5123885071463947512),
        name: 'brincoAnimal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(39, 1502901813362012467),
        name: 'brincoAnimalOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(40, 5172960124157000080),
        name: 'lastSyncedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(41, 3714669193856084163),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(42, 5184526403741674461),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(43, 8367300470122071856),
        name: 'parentReference',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1181959374385839599),
    name: 'ProdutorEntity',
    lastPropertyId: const obx_int.IdUid(8, 898746244557042397),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3902909207689645162),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4142040733915914247),
        name: 'firestoreId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 3403879259921012878),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4460820781105592614),
        name: 'liberado',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2689252183551979486),
        name: 'uidTecnico',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 420360452662675396),
        name: 'uidPerson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4375455145997856015),
        name: 'lastSyncedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5098679746480498469),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 898746244557042397),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7455302727451453424),
    name: 'PropriedadesEntity',
    lastPropertyId: const obx_int.IdUid(14, 5861356246789491817),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7481696113920014552),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 25731029128429000),
        name: 'firestoreId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 1825357446875200075),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4368717976784373606),
        name: 'parentReference',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6699076770080097020),
        name: 'uidPersonProdutor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4457445523197686573),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7424172743698781349),
        name: 'displayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1426185073457701357),
        name: 'cpf',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7779629917273012107),
        name: 'endereco',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6608623212432026947),
        name: 'cidade',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 9043730641443403982),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6688892234477481633),
        name: 'diasParaDg',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8459528683907898888),
        name: 'lastSyncedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2056167165437557213),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5861356246789491817),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6571308469525094653),
    name: 'TecnicoEntity',
    lastPropertyId: const obx_int.IdUid(13, 8402828181218221090),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6900158701540574642),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7146657866757276067),
        name: 'firestoreId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 1932596765091961075),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1723160421429251975),
        name: 'uidPerson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7858987735384795097),
        name: 'liberado',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8130353586183589509),
        name: 'limiteProdutoresContratado',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1460803626757015744),
        name: 'quantidadeProdutoresCadastrados',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1991227019722926671),
        name: 'restanteLimiteProdutores',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1899171023615293442),
        name: 'limiteAnimaisContratado',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 95633939449054120),
        name: 'quantidadeAnimaisCadastrados',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8527102315043118733),
        name: 'restanteLimiteAnimais',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4089837042854590953),
        name: 'lastSyncedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6209605553649147449),
        name: 'needsSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8402828181218221090),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 6571308469525094653),
    lastIndexId: const obx_int.IdUid(5, 1932596765091961075),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    PersonEntity: obx_int.EntityDefinition<PersonEntity>(
      model: _entities[0],
      toOneRelations: (PersonEntity object) => [],
      toManyRelations: (PersonEntity object) => {},
      getId: (PersonEntity object) => object.id,
      setId: (PersonEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PersonEntity object, fb.Builder fbb) {
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final dtNascimentoOffset = object.dtNascimento == null
            ? null
            : fbb.writeString(object.dtNascimento!);
        final cpfOffset = object.cpf == null
            ? null
            : fbb.writeString(object.cpf!);
        final uidOffset = object.uid == null
            ? null
            : fbb.writeString(object.uid!);
        final enderecoOffset = object.endereco == null
            ? null
            : fbb.writeString(object.endereco!);
        final cidadeOffset = object.cidade == null
            ? null
            : fbb.writeString(object.cidade!);
        final bairroOffset = object.bairro == null
            ? null
            : fbb.writeString(object.bairro!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final displayNameOffset = object.displayName == null
            ? null
            : fbb.writeString(object.displayName!);
        final photoUrlOffset = object.photoUrl == null
            ? null
            : fbb.writeString(object.photoUrl!);
        final phoneNumberOffset = object.phoneNumber == null
            ? null
            : fbb.writeString(object.phoneNumber!);
        final empresaOffset = object.empresa == null
            ? null
            : fbb.writeString(object.empresa!);
        final tipoOffset = object.tipo == null
            ? null
            : fbb.writeString(object.tipo!);
        fbb.startTable(19);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firestoreIdOffset);
        fbb.addOffset(2, dtNascimentoOffset);
        fbb.addOffset(3, cpfOffset);
        fbb.addOffset(4, uidOffset);
        fbb.addOffset(5, enderecoOffset);
        fbb.addOffset(6, cidadeOffset);
        fbb.addOffset(7, bairroOffset);
        fbb.addOffset(8, emailOffset);
        fbb.addInt64(9, object.createdTime?.millisecondsSinceEpoch);
        fbb.addOffset(10, displayNameOffset);
        fbb.addOffset(11, photoUrlOffset);
        fbb.addOffset(12, phoneNumberOffset);
        fbb.addOffset(13, empresaOffset);
        fbb.addOffset(14, tipoOffset);
        fbb.addInt64(15, object.lastSyncedAt?.millisecondsSinceEpoch);
        fbb.addBool(16, object.needsSync);
        fbb.addBool(17, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final lastSyncedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final dtNascimentoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final cpfParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final enderecoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final cidadeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final bairroParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final createdTimeParam = createdTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdTimeValue);
        final displayNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final photoUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final empresaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final tipoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final lastSyncedAtParam = lastSyncedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedAtValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          36,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          38,
          false,
        );
        final object = PersonEntity(
          id: idParam,
          firestoreId: firestoreIdParam,
          dtNascimento: dtNascimentoParam,
          cpf: cpfParam,
          uid: uidParam,
          endereco: enderecoParam,
          cidade: cidadeParam,
          bairro: bairroParam,
          email: emailParam,
          createdTime: createdTimeParam,
          displayName: displayNameParam,
          photoUrl: photoUrlParam,
          phoneNumber: phoneNumberParam,
          empresa: empresaParam,
          tipo: tipoParam,
          lastSyncedAt: lastSyncedAtParam,
          needsSync: needsSyncParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    AnimaisProdutoresEntity: obx_int.EntityDefinition<AnimaisProdutoresEntity>(
      model: _entities[1],
      toOneRelations: (AnimaisProdutoresEntity object) => [],
      toManyRelations: (AnimaisProdutoresEntity object) => {},
      getId: (AnimaisProdutoresEntity object) => object.id,
      setId: (AnimaisProdutoresEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AnimaisProdutoresEntity object, fb.Builder fbb) {
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final uidTecnicoPropriedadeOffset = object.uidTecnicoPropriedade == null
            ? null
            : fbb.writeString(object.uidTecnicoPropriedade!);
        final nomeAnimalOffset = object.nomeAnimal == null
            ? null
            : fbb.writeString(object.nomeAnimal!);
        final racaAnimalOffset = object.racaAnimal == null
            ? null
            : fbb.writeString(object.racaAnimal!);
        final pesoAnimalOffset = object.pesoAnimal == null
            ? null
            : fbb.writeString(object.pesoAnimal!);
        final dtNascimentoOffset = object.dtNascimento == null
            ? null
            : fbb.writeString(object.dtNascimento!);
        final touroOffset = object.touro == null
            ? null
            : fbb.writeString(object.touro!);
        final vacaOffset = object.vaca == null
            ? null
            : fbb.writeString(object.vaca!);
        final statusOffset = object.status == null
            ? null
            : fbb.writeString(object.status!);
        final grupoAnimalOffset = object.grupoAnimal == null
            ? null
            : fbb.writeString(object.grupoAnimal!);
        final dtUltimaInseminacaoOffset = object.dtUltimaInseminacao == null
            ? null
            : fbb.writeString(object.dtUltimaInseminacao!);
        final dtUltimoPartoOffset = object.dtUltimoParto == null
            ? null
            : fbb.writeString(object.dtUltimoParto!);
        final dtPartoPrevistoOffset = object.dtPartoPrevisto == null
            ? null
            : fbb.writeString(object.dtPartoPrevisto!);
        final dtSecPrevistaOffset = object.dtSecPrevista == null
            ? null
            : fbb.writeString(object.dtSecPrevista!);
        final dtPrePartoPrevistaOffset = object.dtPrePartoPrevista == null
            ? null
            : fbb.writeString(object.dtPrePartoPrevista!);
        final dtPPOffset = object.dtPP == null
            ? null
            : fbb.writeString(object.dtPP!);
        final dtDgMaisOffset = object.dtDgMais == null
            ? null
            : fbb.writeString(object.dtDgMais!);
        final dtDgMenosOffset = object.dtDgMenos == null
            ? null
            : fbb.writeString(object.dtDgMenos!);
        final dtAbortoOffset = object.dtAborto == null
            ? null
            : fbb.writeString(object.dtAborto!);
        final dtSecagemOffset = object.dtSecagem == null
            ? null
            : fbb.writeString(object.dtSecagem!);
        final dtUltimoPPOffset = object.dtUltimoPP == null
            ? null
            : fbb.writeString(object.dtUltimoPP!);
        final nomeTouroUltimaInseminacaoOffset =
            object.nomeTouroUltimaInseminacao == null
            ? null
            : fbb.writeString(object.nomeTouroUltimaInseminacao!);
        final dtPrePartoOffset = object.dtPreParto == null
            ? null
            : fbb.writeString(object.dtPreParto!);
        final motivoDescarteAnimalOffset = object.motivoDescarteAnimal == null
            ? null
            : fbb.writeString(object.motivoDescarteAnimal!);
        final dtDescarteAnimalOffset = object.dtDescarteAnimal == null
            ? null
            : fbb.writeString(object.dtDescarteAnimal!);
        final dtUltimaAcaoOffset = object.dtUltimaAcao == null
            ? null
            : fbb.writeString(object.dtUltimaAcao!);
        final nomeBrincoConcatOffset = object.nomeBrincoConcat == null
            ? null
            : fbb.writeString(object.nomeBrincoConcat!);
        final dtUltimoPartoContingenciaOffset =
            object.dtUltimoPartoContingencia == null
            ? null
            : fbb.writeString(object.dtUltimoPartoContingencia!);
        final parentReferenceOffset = object.parentReference == null
            ? null
            : fbb.writeString(object.parentReference!);
        fbb.startTable(44);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firestoreIdOffset);
        fbb.addOffset(2, uidTecnicoPropriedadeOffset);
        fbb.addOffset(3, nomeAnimalOffset);
        fbb.addOffset(4, racaAnimalOffset);
        fbb.addOffset(5, pesoAnimalOffset);
        fbb.addOffset(6, dtNascimentoOffset);
        fbb.addOffset(7, touroOffset);
        fbb.addOffset(8, vacaOffset);
        fbb.addOffset(9, statusOffset);
        fbb.addOffset(10, grupoAnimalOffset);
        fbb.addOffset(11, dtUltimaInseminacaoOffset);
        fbb.addOffset(12, dtUltimoPartoOffset);
        fbb.addBool(13, object.liberaInseminacao);
        fbb.addOffset(14, dtPartoPrevistoOffset);
        fbb.addOffset(15, dtSecPrevistaOffset);
        fbb.addOffset(16, dtPrePartoPrevistaOffset);
        fbb.addOffset(17, dtPPOffset);
        fbb.addOffset(18, dtDgMaisOffset);
        fbb.addOffset(19, dtDgMenosOffset);
        fbb.addOffset(20, dtAbortoOffset);
        fbb.addOffset(21, dtSecagemOffset);
        fbb.addOffset(22, dtUltimoPPOffset);
        fbb.addOffset(23, nomeTouroUltimaInseminacaoOffset);
        fbb.addInt64(24, object.totalInseminacoes);
        fbb.addInt64(25, object.totalPartos);
        fbb.addOffset(26, dtPrePartoOffset);
        fbb.addOffset(27, motivoDescarteAnimalOffset);
        fbb.addOffset(28, dtDescarteAnimalOffset);
        fbb.addOffset(29, dtUltimaAcaoOffset);
        fbb.addInt64(
          30,
          object.compararDtUltimaInseminacao?.millisecondsSinceEpoch,
        );
        fbb.addOffset(31, nomeBrincoConcatOffset);
        fbb.addInt64(32, object.idGrupoAnimal);
        fbb.addOffset(33, dtUltimoPartoContingenciaOffset);
        fbb.addInt64(34, object.idStatusAnimal);
        fbb.addInt64(35, object.dtInducaoLactacao?.millisecondsSinceEpoch);
        fbb.addInt64(36, object.dtDesmame?.millisecondsSinceEpoch);
        fbb.addInt64(37, object.brincoAnimal);
        fbb.addInt64(38, object.brincoAnimalOrder);
        fbb.addInt64(39, object.lastSyncedAt?.millisecondsSinceEpoch);
        fbb.addBool(40, object.needsSync);
        fbb.addBool(41, object.isDeleted);
        fbb.addOffset(42, parentReferenceOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final compararDtUltimaInseminacaoValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 64);
        final dtInducaoLactacaoValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          74,
        );
        final dtDesmameValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          76,
        );
        final lastSyncedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          82,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final parentReferenceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 88);
        final uidTecnicoPropriedadeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final nomeAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final racaAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final pesoAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final dtNascimentoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final touroParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final vacaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final grupoAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final dtUltimaInseminacaoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final dtUltimoPartoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final liberaInseminacaoParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final dtPartoPrevistoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final dtSecPrevistaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final dtPrePartoPrevistaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final dtPPParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final dtDgMaisParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final dtDgMenosParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final dtAbortoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 44);
        final dtSecagemParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final dtUltimoPPParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final nomeTouroUltimaInseminacaoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final totalInseminacoesParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          52,
        );
        final totalPartosParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          54,
        );
        final dtPrePartoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 56);
        final motivoDescarteAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 58);
        final dtDescarteAnimalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 60);
        final dtUltimaAcaoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 62);
        final compararDtUltimaInseminacaoParam =
            compararDtUltimaInseminacaoValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(
                compararDtUltimaInseminacaoValue,
              );
        final nomeBrincoConcatParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 66);
        final idGrupoAnimalParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          68,
        );
        final dtUltimoPartoContingenciaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 70);
        final idStatusAnimalParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          72,
        );
        final dtInducaoLactacaoParam = dtInducaoLactacaoValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dtInducaoLactacaoValue);
        final dtDesmameParam = dtDesmameValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dtDesmameValue);
        final brincoAnimalParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          78,
        );
        final brincoAnimalOrderParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          80,
        );
        final lastSyncedAtParam = lastSyncedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedAtValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          84,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          86,
          false,
        );
        final object = AnimaisProdutoresEntity(
          id: idParam,
          firestoreId: firestoreIdParam,
          parentReference: parentReferenceParam,
          uidTecnicoPropriedade: uidTecnicoPropriedadeParam,
          nomeAnimal: nomeAnimalParam,
          racaAnimal: racaAnimalParam,
          pesoAnimal: pesoAnimalParam,
          dtNascimento: dtNascimentoParam,
          touro: touroParam,
          vaca: vacaParam,
          status: statusParam,
          grupoAnimal: grupoAnimalParam,
          dtUltimaInseminacao: dtUltimaInseminacaoParam,
          dtUltimoParto: dtUltimoPartoParam,
          liberaInseminacao: liberaInseminacaoParam,
          dtPartoPrevisto: dtPartoPrevistoParam,
          dtSecPrevista: dtSecPrevistaParam,
          dtPrePartoPrevista: dtPrePartoPrevistaParam,
          dtPP: dtPPParam,
          dtDgMais: dtDgMaisParam,
          dtDgMenos: dtDgMenosParam,
          dtAborto: dtAbortoParam,
          dtSecagem: dtSecagemParam,
          dtUltimoPP: dtUltimoPPParam,
          nomeTouroUltimaInseminacao: nomeTouroUltimaInseminacaoParam,
          totalInseminacoes: totalInseminacoesParam,
          totalPartos: totalPartosParam,
          dtPreParto: dtPrePartoParam,
          motivoDescarteAnimal: motivoDescarteAnimalParam,
          dtDescarteAnimal: dtDescarteAnimalParam,
          dtUltimaAcao: dtUltimaAcaoParam,
          compararDtUltimaInseminacao: compararDtUltimaInseminacaoParam,
          nomeBrincoConcat: nomeBrincoConcatParam,
          idGrupoAnimal: idGrupoAnimalParam,
          dtUltimoPartoContingencia: dtUltimoPartoContingenciaParam,
          idStatusAnimal: idStatusAnimalParam,
          dtInducaoLactacao: dtInducaoLactacaoParam,
          dtDesmame: dtDesmameParam,
          brincoAnimal: brincoAnimalParam,
          brincoAnimalOrder: brincoAnimalOrderParam,
          lastSyncedAt: lastSyncedAtParam,
          needsSync: needsSyncParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    ProdutorEntity: obx_int.EntityDefinition<ProdutorEntity>(
      model: _entities[2],
      toOneRelations: (ProdutorEntity object) => [],
      toManyRelations: (ProdutorEntity object) => {},
      getId: (ProdutorEntity object) => object.id,
      setId: (ProdutorEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ProdutorEntity object, fb.Builder fbb) {
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final uidTecnicoOffset = object.uidTecnico == null
            ? null
            : fbb.writeString(object.uidTecnico!);
        final uidPersonOffset = object.uidPerson == null
            ? null
            : fbb.writeString(object.uidPerson!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firestoreIdOffset);
        fbb.addBool(2, object.liberado);
        fbb.addOffset(3, uidTecnicoOffset);
        fbb.addOffset(4, uidPersonOffset);
        fbb.addInt64(5, object.lastSyncedAt?.millisecondsSinceEpoch);
        fbb.addBool(6, object.needsSync);
        fbb.addBool(7, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastSyncedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final liberadoParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final uidTecnicoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final uidPersonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final lastSyncedAtParam = lastSyncedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedAtValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = ProdutorEntity(
          id: idParam,
          firestoreId: firestoreIdParam,
          liberado: liberadoParam,
          uidTecnico: uidTecnicoParam,
          uidPerson: uidPersonParam,
          lastSyncedAt: lastSyncedAtParam,
          needsSync: needsSyncParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    PropriedadesEntity: obx_int.EntityDefinition<PropriedadesEntity>(
      model: _entities[3],
      toOneRelations: (PropriedadesEntity object) => [],
      toManyRelations: (PropriedadesEntity object) => {},
      getId: (PropriedadesEntity object) => object.id,
      setId: (PropriedadesEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PropriedadesEntity object, fb.Builder fbb) {
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final parentReferenceOffset = object.parentReference == null
            ? null
            : fbb.writeString(object.parentReference!);
        final uidPersonProdutorOffset = object.uidPersonProdutor == null
            ? null
            : fbb.writeString(object.uidPersonProdutor!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final displayNameOffset = object.displayName == null
            ? null
            : fbb.writeString(object.displayName!);
        final cpfOffset = object.cpf == null
            ? null
            : fbb.writeString(object.cpf!);
        final enderecoOffset = object.endereco == null
            ? null
            : fbb.writeString(object.endereco!);
        final cidadeOffset = object.cidade == null
            ? null
            : fbb.writeString(object.cidade!);
        final phoneNumberOffset = object.phoneNumber == null
            ? null
            : fbb.writeString(object.phoneNumber!);
        final diasParaDgOffset = object.diasParaDg == null
            ? null
            : fbb.writeString(object.diasParaDg!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firestoreIdOffset);
        fbb.addOffset(2, parentReferenceOffset);
        fbb.addOffset(3, uidPersonProdutorOffset);
        fbb.addOffset(4, emailOffset);
        fbb.addOffset(5, displayNameOffset);
        fbb.addOffset(6, cpfOffset);
        fbb.addOffset(7, enderecoOffset);
        fbb.addOffset(8, cidadeOffset);
        fbb.addOffset(9, phoneNumberOffset);
        fbb.addOffset(10, diasParaDgOffset);
        fbb.addInt64(11, object.lastSyncedAt?.millisecondsSinceEpoch);
        fbb.addBool(12, object.needsSync);
        fbb.addBool(13, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastSyncedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final parentReferenceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final uidPersonProdutorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final displayNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final cpfParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final enderecoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final cidadeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final diasParaDgParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final lastSyncedAtParam = lastSyncedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedAtValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final object = PropriedadesEntity(
          id: idParam,
          firestoreId: firestoreIdParam,
          parentReference: parentReferenceParam,
          uidPersonProdutor: uidPersonProdutorParam,
          email: emailParam,
          displayName: displayNameParam,
          cpf: cpfParam,
          endereco: enderecoParam,
          cidade: cidadeParam,
          phoneNumber: phoneNumberParam,
          diasParaDg: diasParaDgParam,
          lastSyncedAt: lastSyncedAtParam,
          needsSync: needsSyncParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    TecnicoEntity: obx_int.EntityDefinition<TecnicoEntity>(
      model: _entities[4],
      toOneRelations: (TecnicoEntity object) => [],
      toManyRelations: (TecnicoEntity object) => {},
      getId: (TecnicoEntity object) => object.id,
      setId: (TecnicoEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TecnicoEntity object, fb.Builder fbb) {
        final firestoreIdOffset = object.firestoreId == null
            ? null
            : fbb.writeString(object.firestoreId!);
        final uidPersonOffset = object.uidPerson == null
            ? null
            : fbb.writeString(object.uidPerson!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, firestoreIdOffset);
        fbb.addOffset(2, uidPersonOffset);
        fbb.addBool(3, object.liberado);
        fbb.addInt64(4, object.limiteProdutoresContratado);
        fbb.addInt64(5, object.quantidadeProdutoresCadastrados);
        fbb.addInt64(6, object.restanteLimiteProdutores);
        fbb.addInt64(7, object.limiteAnimaisContratado);
        fbb.addInt64(8, object.quantidadeAnimaisCadastrados);
        fbb.addInt64(9, object.restanteLimiteAnimais);
        fbb.addInt64(10, object.lastSyncedAt?.millisecondsSinceEpoch);
        fbb.addBool(11, object.needsSync);
        fbb.addBool(12, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastSyncedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final firestoreIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final uidPersonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final liberadoParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final limiteProdutoresContratadoParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 12);
        final quantidadeProdutoresCadastradosParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 14);
        final restanteLimiteProdutoresParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final limiteAnimaisContratadoParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 18);
        final quantidadeAnimaisCadastradosParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 20);
        final restanteLimiteAnimaisParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 22);
        final lastSyncedAtParam = lastSyncedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedAtValue);
        final needsSyncParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final object = TecnicoEntity(
          id: idParam,
          firestoreId: firestoreIdParam,
          uidPerson: uidPersonParam,
          liberado: liberadoParam,
          limiteProdutoresContratado: limiteProdutoresContratadoParam,
          quantidadeProdutoresCadastrados: quantidadeProdutoresCadastradosParam,
          restanteLimiteProdutores: restanteLimiteProdutoresParam,
          limiteAnimaisContratado: limiteAnimaisContratadoParam,
          quantidadeAnimaisCadastrados: quantidadeAnimaisCadastradosParam,
          restanteLimiteAnimais: restanteLimiteAnimaisParam,
          lastSyncedAt: lastSyncedAtParam,
          needsSync: needsSyncParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PersonEntity] entity fields to define ObjectBox queries.
class PersonEntity_ {
  /// See [PersonEntity.id].
  static final id = obx.QueryIntegerProperty<PersonEntity>(
    _entities[0].properties[0],
  );

  /// See [PersonEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[1],
  );

  /// See [PersonEntity.dtNascimento].
  static final dtNascimento = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[2],
  );

  /// See [PersonEntity.cpf].
  static final cpf = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[3],
  );

  /// See [PersonEntity.uid].
  static final uid = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[4],
  );

  /// See [PersonEntity.endereco].
  static final endereco = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[5],
  );

  /// See [PersonEntity.cidade].
  static final cidade = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[6],
  );

  /// See [PersonEntity.bairro].
  static final bairro = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[7],
  );

  /// See [PersonEntity.email].
  static final email = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[8],
  );

  /// See [PersonEntity.createdTime].
  static final createdTime = obx.QueryDateProperty<PersonEntity>(
    _entities[0].properties[9],
  );

  /// See [PersonEntity.displayName].
  static final displayName = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[10],
  );

  /// See [PersonEntity.photoUrl].
  static final photoUrl = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[11],
  );

  /// See [PersonEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[12],
  );

  /// See [PersonEntity.empresa].
  static final empresa = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[13],
  );

  /// See [PersonEntity.tipo].
  static final tipo = obx.QueryStringProperty<PersonEntity>(
    _entities[0].properties[14],
  );

  /// See [PersonEntity.lastSyncedAt].
  static final lastSyncedAt = obx.QueryDateProperty<PersonEntity>(
    _entities[0].properties[15],
  );

  /// See [PersonEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<PersonEntity>(
    _entities[0].properties[16],
  );

  /// See [PersonEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<PersonEntity>(
    _entities[0].properties[17],
  );
}

/// [AnimaisProdutoresEntity] entity fields to define ObjectBox queries.
class AnimaisProdutoresEntity_ {
  /// See [AnimaisProdutoresEntity.id].
  static final id = obx.QueryIntegerProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[0],
  );

  /// See [AnimaisProdutoresEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[1],
  );

  /// See [AnimaisProdutoresEntity.uidTecnicoPropriedade].
  static final uidTecnicoPropriedade =
      obx.QueryStringProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[2],
      );

  /// See [AnimaisProdutoresEntity.nomeAnimal].
  static final nomeAnimal = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[3],
  );

  /// See [AnimaisProdutoresEntity.racaAnimal].
  static final racaAnimal = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[4],
  );

  /// See [AnimaisProdutoresEntity.pesoAnimal].
  static final pesoAnimal = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[5],
  );

  /// See [AnimaisProdutoresEntity.dtNascimento].
  static final dtNascimento = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[6],
  );

  /// See [AnimaisProdutoresEntity.touro].
  static final touro = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[7],
  );

  /// See [AnimaisProdutoresEntity.vaca].
  static final vaca = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[8],
  );

  /// See [AnimaisProdutoresEntity.status].
  static final status = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[9],
  );

  /// See [AnimaisProdutoresEntity.grupoAnimal].
  static final grupoAnimal = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[10],
  );

  /// See [AnimaisProdutoresEntity.dtUltimaInseminacao].
  static final dtUltimaInseminacao =
      obx.QueryStringProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[11],
      );

  /// See [AnimaisProdutoresEntity.dtUltimoParto].
  static final dtUltimoParto = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[12],
  );

  /// See [AnimaisProdutoresEntity.liberaInseminacao].
  static final liberaInseminacao =
      obx.QueryBooleanProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[13],
      );

  /// See [AnimaisProdutoresEntity.dtPartoPrevisto].
  static final dtPartoPrevisto =
      obx.QueryStringProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[14],
      );

  /// See [AnimaisProdutoresEntity.dtSecPrevista].
  static final dtSecPrevista = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[15],
  );

  /// See [AnimaisProdutoresEntity.dtPrePartoPrevista].
  static final dtPrePartoPrevista =
      obx.QueryStringProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[16],
      );

  /// See [AnimaisProdutoresEntity.dtPP].
  static final dtPP = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[17],
  );

  /// See [AnimaisProdutoresEntity.dtDgMais].
  static final dtDgMais = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[18],
  );

  /// See [AnimaisProdutoresEntity.dtDgMenos].
  static final dtDgMenos = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[19],
  );

  /// See [AnimaisProdutoresEntity.dtAborto].
  static final dtAborto = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[20],
  );

  /// See [AnimaisProdutoresEntity.dtSecagem].
  static final dtSecagem = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[21],
  );

  /// See [AnimaisProdutoresEntity.dtUltimoPP].
  static final dtUltimoPP = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[22],
  );

  /// See [AnimaisProdutoresEntity.nomeTouroUltimaInseminacao].
  static final nomeTouroUltimaInseminacao =
      obx.QueryStringProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[23],
      );

  /// See [AnimaisProdutoresEntity.totalInseminacoes].
  static final totalInseminacoes =
      obx.QueryIntegerProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[24],
      );

  /// See [AnimaisProdutoresEntity.totalPartos].
  static final totalPartos = obx.QueryIntegerProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[25],
  );

  /// See [AnimaisProdutoresEntity.dtPreParto].
  static final dtPreParto = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[26],
  );

  /// See [AnimaisProdutoresEntity.motivoDescarteAnimal].
  static final motivoDescarteAnimal =
      obx.QueryStringProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[27],
      );

  /// See [AnimaisProdutoresEntity.dtDescarteAnimal].
  static final dtDescarteAnimal =
      obx.QueryStringProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[28],
      );

  /// See [AnimaisProdutoresEntity.dtUltimaAcao].
  static final dtUltimaAcao = obx.QueryStringProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[29],
  );

  /// See [AnimaisProdutoresEntity.compararDtUltimaInseminacao].
  static final compararDtUltimaInseminacao =
      obx.QueryDateProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[30],
      );

  /// See [AnimaisProdutoresEntity.nomeBrincoConcat].
  static final nomeBrincoConcat =
      obx.QueryStringProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[31],
      );

  /// See [AnimaisProdutoresEntity.idGrupoAnimal].
  static final idGrupoAnimal =
      obx.QueryIntegerProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[32],
      );

  /// See [AnimaisProdutoresEntity.dtUltimoPartoContingencia].
  static final dtUltimoPartoContingencia =
      obx.QueryStringProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[33],
      );

  /// See [AnimaisProdutoresEntity.idStatusAnimal].
  static final idStatusAnimal =
      obx.QueryIntegerProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[34],
      );

  /// See [AnimaisProdutoresEntity.dtInducaoLactacao].
  static final dtInducaoLactacao =
      obx.QueryDateProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[35],
      );

  /// See [AnimaisProdutoresEntity.dtDesmame].
  static final dtDesmame = obx.QueryDateProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[36],
  );

  /// See [AnimaisProdutoresEntity.brincoAnimal].
  static final brincoAnimal = obx.QueryIntegerProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[37],
  );

  /// See [AnimaisProdutoresEntity.brincoAnimalOrder].
  static final brincoAnimalOrder =
      obx.QueryIntegerProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[38],
      );

  /// See [AnimaisProdutoresEntity.lastSyncedAt].
  static final lastSyncedAt = obx.QueryDateProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[39],
  );

  /// See [AnimaisProdutoresEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[40],
  );

  /// See [AnimaisProdutoresEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<AnimaisProdutoresEntity>(
    _entities[1].properties[41],
  );

  /// See [AnimaisProdutoresEntity.parentReference].
  static final parentReference =
      obx.QueryStringProperty<AnimaisProdutoresEntity>(
        _entities[1].properties[42],
      );
}

/// [ProdutorEntity] entity fields to define ObjectBox queries.
class ProdutorEntity_ {
  /// See [ProdutorEntity.id].
  static final id = obx.QueryIntegerProperty<ProdutorEntity>(
    _entities[2].properties[0],
  );

  /// See [ProdutorEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<ProdutorEntity>(
    _entities[2].properties[1],
  );

  /// See [ProdutorEntity.liberado].
  static final liberado = obx.QueryBooleanProperty<ProdutorEntity>(
    _entities[2].properties[2],
  );

  /// See [ProdutorEntity.uidTecnico].
  static final uidTecnico = obx.QueryStringProperty<ProdutorEntity>(
    _entities[2].properties[3],
  );

  /// See [ProdutorEntity.uidPerson].
  static final uidPerson = obx.QueryStringProperty<ProdutorEntity>(
    _entities[2].properties[4],
  );

  /// See [ProdutorEntity.lastSyncedAt].
  static final lastSyncedAt = obx.QueryDateProperty<ProdutorEntity>(
    _entities[2].properties[5],
  );

  /// See [ProdutorEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<ProdutorEntity>(
    _entities[2].properties[6],
  );

  /// See [ProdutorEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<ProdutorEntity>(
    _entities[2].properties[7],
  );
}

/// [PropriedadesEntity] entity fields to define ObjectBox queries.
class PropriedadesEntity_ {
  /// See [PropriedadesEntity.id].
  static final id = obx.QueryIntegerProperty<PropriedadesEntity>(
    _entities[3].properties[0],
  );

  /// See [PropriedadesEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<PropriedadesEntity>(
    _entities[3].properties[1],
  );

  /// See [PropriedadesEntity.parentReference].
  static final parentReference = obx.QueryStringProperty<PropriedadesEntity>(
    _entities[3].properties[2],
  );

  /// See [PropriedadesEntity.uidPersonProdutor].
  static final uidPersonProdutor = obx.QueryStringProperty<PropriedadesEntity>(
    _entities[3].properties[3],
  );

  /// See [PropriedadesEntity.email].
  static final email = obx.QueryStringProperty<PropriedadesEntity>(
    _entities[3].properties[4],
  );

  /// See [PropriedadesEntity.displayName].
  static final displayName = obx.QueryStringProperty<PropriedadesEntity>(
    _entities[3].properties[5],
  );

  /// See [PropriedadesEntity.cpf].
  static final cpf = obx.QueryStringProperty<PropriedadesEntity>(
    _entities[3].properties[6],
  );

  /// See [PropriedadesEntity.endereco].
  static final endereco = obx.QueryStringProperty<PropriedadesEntity>(
    _entities[3].properties[7],
  );

  /// See [PropriedadesEntity.cidade].
  static final cidade = obx.QueryStringProperty<PropriedadesEntity>(
    _entities[3].properties[8],
  );

  /// See [PropriedadesEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<PropriedadesEntity>(
    _entities[3].properties[9],
  );

  /// See [PropriedadesEntity.diasParaDg].
  static final diasParaDg = obx.QueryStringProperty<PropriedadesEntity>(
    _entities[3].properties[10],
  );

  /// See [PropriedadesEntity.lastSyncedAt].
  static final lastSyncedAt = obx.QueryDateProperty<PropriedadesEntity>(
    _entities[3].properties[11],
  );

  /// See [PropriedadesEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<PropriedadesEntity>(
    _entities[3].properties[12],
  );

  /// See [PropriedadesEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<PropriedadesEntity>(
    _entities[3].properties[13],
  );
}

/// [TecnicoEntity] entity fields to define ObjectBox queries.
class TecnicoEntity_ {
  /// See [TecnicoEntity.id].
  static final id = obx.QueryIntegerProperty<TecnicoEntity>(
    _entities[4].properties[0],
  );

  /// See [TecnicoEntity.firestoreId].
  static final firestoreId = obx.QueryStringProperty<TecnicoEntity>(
    _entities[4].properties[1],
  );

  /// See [TecnicoEntity.uidPerson].
  static final uidPerson = obx.QueryStringProperty<TecnicoEntity>(
    _entities[4].properties[2],
  );

  /// See [TecnicoEntity.liberado].
  static final liberado = obx.QueryBooleanProperty<TecnicoEntity>(
    _entities[4].properties[3],
  );

  /// See [TecnicoEntity.limiteProdutoresContratado].
  static final limiteProdutoresContratado =
      obx.QueryIntegerProperty<TecnicoEntity>(_entities[4].properties[4]);

  /// See [TecnicoEntity.quantidadeProdutoresCadastrados].
  static final quantidadeProdutoresCadastrados =
      obx.QueryIntegerProperty<TecnicoEntity>(_entities[4].properties[5]);

  /// See [TecnicoEntity.restanteLimiteProdutores].
  static final restanteLimiteProdutores =
      obx.QueryIntegerProperty<TecnicoEntity>(_entities[4].properties[6]);

  /// See [TecnicoEntity.limiteAnimaisContratado].
  static final limiteAnimaisContratado =
      obx.QueryIntegerProperty<TecnicoEntity>(_entities[4].properties[7]);

  /// See [TecnicoEntity.quantidadeAnimaisCadastrados].
  static final quantidadeAnimaisCadastrados =
      obx.QueryIntegerProperty<TecnicoEntity>(_entities[4].properties[8]);

  /// See [TecnicoEntity.restanteLimiteAnimais].
  static final restanteLimiteAnimais = obx.QueryIntegerProperty<TecnicoEntity>(
    _entities[4].properties[9],
  );

  /// See [TecnicoEntity.lastSyncedAt].
  static final lastSyncedAt = obx.QueryDateProperty<TecnicoEntity>(
    _entities[4].properties[10],
  );

  /// See [TecnicoEntity.needsSync].
  static final needsSync = obx.QueryBooleanProperty<TecnicoEntity>(
    _entities[4].properties[11],
  );

  /// See [TecnicoEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<TecnicoEntity>(
    _entities[4].properties[12],
  );
}
