/// Descrições fixas de grupos e raças.
///
/// Antes ficavam em `FFAppState.grupo` / `FFAppState.racas` (listas de structs),
/// que nunca eram escritas — eram constantes de fato, usadas como fallback das
/// opções de dropdown (quando a lista vinda do Firestore está vazia), via
/// `.map((e) => e.descricao)`. Movidas para cá como `List<String>` const,
/// eliminando os campos do god object `FFAppState`. As queries reativas de
/// Firestore (`gruposGeral`/`racasGeral`) permanecem em `FFAppState`.
const kGruposDescricoes = <String>[
  'Touros',
  'Bezerros',
  'Semêns',
  'Bezerras',
  'Novilhas',
  'Vacas',
];

const kRacasDescricoes = <String>[
  'Aberdeen Angus',
  'Ayrshire',
  'Romagnola',
  'Gelbvieh',
  'Holandesa',
  'Guernsey',
  'Tabapuã',
  'Belmont Red',
  'Charolesa',
  'Shorthorn',
  'Chianina',
  'Canchim',
  'Nelore Mocho',
  'Limousin',
  'Brahvieh',
  'Sindi',
  'Belted Galloway',
  'Barzona',
  'Brahaman Africano',
  'Galloway',
  'Simental-Pardo',
  'Salers',
  'Simmental',
  'Marchigiana',
  'Brahman',
  'Hereford',
  'Wagyu',
  'Indubrasil',
  'Devon',
  'Texas Longhorn',
  'Highland',
  'Santa Gertrudis',
  'Dexter',
  'Murray Grey',
  'Red Angus',
  'Piedmontese',
  'Nelore',
  'Bonsmara',
  'Kerry',
  'Jersey',
  'Zebu',
  'Normando',
  'Tuli',
  'Gir',
  'Caracu',
  'Maine-Anjou',
  'Senepol',
  'Angus',
  'Pardo-Suíço',
  'Brangus',
];
